### ISSUE TITLE
how to further support rollup-plugin-dts?

### ISSUE THREAD

**Issue by arshaw** [Swatinem/rollup-plugin-dts#105]
Your project rollup-plugin-dts has been invaluable for my project! I'm the author of [FullCalendar](https://fullcalendar.io/) and I use it to combine all my dts files into one.

I tried the GH sponsor button, but it only allows me to contribute $1 per month. Could you maybe create a new contribution tier? I'm hoping to contribute $20 per month, for beer/coffee money or whatever. Thanks!

**Comment by Swatinem** [comment]
Oh wow, I’m super humbled ;-) Glad you like it!

Also, I’m standing on the shoulders of giants here, whatever I did wouldn’t be possible without rollup itself.

Skimming through your setup, I saw that you patch some things yourself:

https://github.com/fullcalendar/fullcalendar/blob/7a73577a78be1dc5941e58c49c740c2b0d161a90/rollup.packages.js#L120-L169

Would be nice to maybe reduce those further to properly fix them. In general, tsc only emits inline `import()` types when it does type inference, so explicitly declaring return types usually helps in those cases.

**Comment by arshaw** [comment]
Hey @Swatinem , thanks for the reply! Sorry for the delay, I wanted to get all my ducks in a row before responding.

Nearly all of the hacks I'm employing are related to the way TSC outputs .d.ts files, thus out of the scope of your project. I just annotated my source file to link to the various tickets:

https://github.com/fullcalendar/fullcalendar/commit/5a0d509e09d405a161a0083eb6681fddca43a544

The one problem that **IS** in your projects wheelhouse is #106, which I just made a ticket for.

Since I made a separate ticket for that, and since you reconfigured your Sponsors stuff, I'll close this ticket. Thanks again!!

**Comment by arshaw** [comment]
Responding to your comment about inline `import()` ... yes, I've found that explicitly declaring a function's return value helps with this. However, I really like TypeScript's type inferencing and leverage it quite a bit. I want to continue to use it, and I don't really want to sprinkle my code with explicit types in a reactionary way to solve this. Even if I did that, I would still need to somehow lint the combined .d.ts file to ensure I didn't miss any.

**Comment by Swatinem** [comment]
Well thank you ;-)

So the bug on my end was super easy to fix actually. And interesting that most of your other issues are actually with typescript itself.

I do get your argument about inference being super convenient, my reasoning here is basically:

* your return types are just as much public API as your argument types, so its good to be explicit in general also to avoid accidental API breaks
* Depending on the compiler design, having explicit annotations is better because the type checker does not need to look at the function body at all to figure out whats going on. No idea how typescript works with this in mind though.

**Comment by arshaw** [comment]
Thank you so much for the fix!!!! ([I commented on the ticket](https://github.com/Swatinem/rollup-plugin-dts/issues/106#issuecomment-662137867))

You might be right about typing the return value of functions. If the params are explicitly typed, why not do the same for the return value.

There's a typescript-aware eslint rule for this I might employ: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md

Thanks for your perspective.
