### ISSUE TITLE
dts and .vue

### ISSUE THREAD

**Issue by regenrek** [Swatinem/rollup-plugin-dts#107]
Hi,

I'm stuck with this since some hours. I create type definitions with `tsc --emitDeclarationOnly` inside `typings` 
folder. Inside rollup I do something like this:

```
  configs.push({
    input: `./typings/${pkg}/index.d.ts`,
    output: {
      file: `dist/${pkg}/index.d.ts`,
      format: 'es',
    },
    plugins: [
      dts(),
    ],
  })
```
The problem now is that I've `component.vue` files with type declarations like `index.d.ts`

```
import FooComponent from './FooComponent.vue';
export { FooComponent };
```

When I build with rollup I get

```
[!] Error: Could not resolve './FooComponent.vue' from typings/ui/FooComponent/index.d.ts
```

Any ideas?

**Comment by Swatinem** [comment]
Where does typescript get the types from? Is that some kind of plugin? Well in theory, you could put any kind of plugin in front of `dts` that has a different `resolve` hook.

**Comment by regenrek** [comment]
I guess dts is looking for .vue files inside the typings folder which of course isn't available yet.

I made a minimal reproduce example here: https://github.com/regenrek/vue-dts-rollup

**Comment by fox2081** [comment]
`tsc` command don't generate dts  for vue file. It cannot compile vue files
 
I use `rollup-plugin-typescript2` and `rollup-plugin-vue` to compile and generate dts for vue file,  like `foo.vue.d.ts`, then use this plugin to bundle them;
