### ISSUE TITLE
feature request: omit private class fields from output

### ISSUE THREAD

**Issue by zenmumbler** [Swatinem/rollup-plugin-dts#117]
TypeScript by default outputs private fields when auto-generating d.ts files. While this is probably because TS private is not really private, imo it runs counter to hiding private fields from interface definitions. I can work around this by annotating each private field in exported types with `/** @internal */` and then enabling the `stripInternal` compile flag but that is a pain for many reasons. ES private fields are not supported well enough and I don't want the generated code overhead and I actually do want access to private fields using the debugger/console. This is about hiding implementation details from library client code in code completion and such.

So my feature request for this plugin is: can you omit private fields in the combined dts? Likely this would have to be controlled by some flag. If this can't be done I'll have to write some other plugin that strips all lines starting with `private` myself, but was hoping this fits within the purview of this plugin.

Thank you.

**Comment by Swatinem** [comment]
hm, I was experimenting with this a *long* time ago.

Problem is that TS has structural equality by default, which means you can assign type `A` to something expecting type `B`, if they have the same properties with the same types. private props kind of "break" this, so its more correct in this regard.

TBH, I would not recommend putting something like this into the plugin.

**Comment by zenmumbler** [comment]
OK, fair enough. I will strip them in a separate step. Structural assignment checks are indeed what TS cares about, but the classes in point have a rather elaborate public signature so public interface comparisons are more than adequate. I also believe more in interface-based assignability in JS/TS.

Thanks for your feedback.
