### ISSUE TITLE
Question: Can this be incorporated into existing rollup builds?

### ISSUE THREAD

**Issue by jamiehaywood** [Swatinem/rollup-plugin-dts#118]
As the question kinda states - is it possible to add `dts()` after the rest of the rollup process?

i.e.

```
  plugins: [
    typescript({
      typescript: require('typescript'),
      tsconfig: 'tsconfig.json',
      useTsconfigDeclarationDir: true,
    }),
    terser(),
    dts()
  ],
```

I've tried this, but I'm getting a rollup error.

**Comment by Swatinem** [comment]
No, it has to go on a separate rollup pipeline.
Your normal rollup build does a `.js -> .js`, and the plugin will do `.d.ts -> .d.ts`. Or alternatively, it can also do `.ts -> .d.ts`, but I would very much recommend to run typescript in a separate pass before.

**Comment by Swatinem** [comment]
https://github.com/Swatinem/rollup-plugin-dts/blob/018d1a593d7cbf41cc64657cb86f9a14ff867590/rollup.config.js#L11-L24

This is the example from the repo itself

**Comment by jamiehaywood** [comment]
@Swatinem thanks very much for the example - very helpful. Have a good week 🙂🚀
