### ISSUE TITLE
Cannot set compilerOptions which have enum type

### ISSUE THREAD

**Issue by microshine** [Swatinem/rollup-plugin-dts#12]
@Swatinem thank you for your amazing plugin. It's very useful tool for `TS` + `Rollup` developing

I'm trying to change `target` via `compilerOptions` in plugin. But I can't do it cause `rollup-plugin-dts` doesn't export this enum.

Would it be better to use string for enums like TS options does?

### rollup.config.js
![image](https://user-images.githubusercontent.com/7333669/53499425-663ac880-3ab9-11e9-8668-b965db3f0ac0.png)

### node console
![image](https://user-images.githubusercontent.com/7333669/53499591-b154db80-3ab9-11e9-9c9f-55657185664a.png)

## Environment

| Name | Version |
|---|---|
| rollup | 1.1.2 |
| rollup-plugin-dts | 0.13.0 |
| typescript | 3.3.3 |
| node | 10.13.0 |
| MacOS | 10.14.3 |

**Comment by microshine** [comment]
Sorry, this was my error

I had to import this enum from `typescript` module
```
import { ScriptTarget } from "typescript";
```

**Comment by Swatinem** [comment]
Oh okay… Well ideally you should be able to use this just like the `compilerOptions` from your `tsconfig.json`, but apparently the type that is exported by TS here is the `strictly typed` one, as opposed to the `json schema` one. But meh.

Unless you want to use the plugin with more than one config in parallel, for example when you want to build one bundle for modern engines and one for obsolete browsers, you don’t need to mess with this stuff and should rather just define everything in your `tsconfig.json`.
