### ISSUE TITLE
ts.isNamedTupleMember is not a function

### ISSUE THREAD

**Issue by trusktr** [Swatinem/rollup-plugin-dts#120]
Hello! I'm trying to improve the build process for [`@tween/tween.js`](https://github.com/tweenjs/tween.js/), and decided to give this plugin a try. Perhaps the error indicates an incompatibility with the `dts` plugin and the version of TS that I have?

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
```

### Error Message

```
./.tmp/Index.d.ts → dist/tween.d.ts...
[!] Error: Could not load /home/trusktr/src/lume+tween.js/.tmp/Index.d.ts: ts.isNamedTupleMember is not a function
```

**Comment by trusktr** [comment]
I upgraded from TS ^3.9 to TS ^4.0 and that error went away, but now it says

```
./.tmp/Index.d.ts → dist/tween.d.ts...
[!] Error: Could not load [object Object] (imported by /home/trusktr/src/lume+tween.js/.tmp/Index.d.ts): The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
```

Looks like another API incompatibility.

**Comment by trusktr** [comment]
I downgraded to TypeScript ^3.9 and rollup-plugin-dts 1.4.10, but I get the same exact error in that case too. I'll open a new issue for that.

The OP issue was solved by making sure to use rollup-plugin-dts ^1.4.11 with TS 4 (which is probably a breaking change and should've bumped dts to v2 instead of 1.4.11).

**Comment by Swatinem** [comment]
> which is probably a breaking change and should've bumped dts to v2 instead of 1.4.11

Supporting a new version of TS means using its new APIs. Otherwise I would be on v11 or something already.

I mention this in the readme explicitly: https://github.com/Swatinem/rollup-plugin-dts#compatibility-notice
