### ISSUE TITLE
Error: The "path" argument must be of type string or an instance of Buffer or URL.

### ISSUE THREAD

**Issue by trusktr** [Swatinem/rollup-plugin-dts#121]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Error Message

```
./.tmp/Index.d.ts → dist/tween.d.ts...
[!] Error: Could not load [object Object] (imported by /home/trusktr/src/lume+tween.js/.tmp/Index.d.ts): The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
```

### More Details

I tried this with dts ^1.4.11 and TS ^4.0.3, as well as with dts 1.4.10 and TS 3.9.7 and I get the same error either way.

The error message isn't too helpful; there isn't a stack trace other than from where Rollup reports the error.

### Reproduction

```sh
git clone https://github.com/lume/tween.js
cd tween.js
git checkout rollup-plugin-dts-issue-121
npm install
npm run tsc # creates declaration files that will be used by the rollup build
npm run rollup-build
```

and it should output the error.

**Comment by trusktr** [comment]
Reproduction:

```js
git clone https://github.com/lume/tween.js
cd tween.js
git checkout rollup-plugin-dts-issue-121
npm install
npm run tsc # creates files that will be used by the rollup build
npm run rollup-build
```

and it should output the error.

**Comment by Swatinem** [comment]
You have a super old `0.57` version of rollup that did not yet support returning an object from the `resolveId` hook. Updating that to `@2` fixes the problem.

You should see a warning like this in the console:
```
npm WARN rollup-plugin-dts@1.4.10 requires a peer of rollup@^2.23.0 but none is installed. You must install peer dependencies yourself.
```
