### ISSUE TITLE
Rollup plugin dts adds references to types to all output files when using multiple input files

### ISSUE THREAD

**Issue by bordoley** [Swatinem/rollup-plugin-dts#128]
I have a project with multiple input and output files. Within the project only a subset of the input files include references to node types, but the resulting output files from rollup-plugin-dts all contain references to node in each .d.ts file. 

I believe this is caused by the use of a single global references Set here: https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/index.ts#L61 which ideally should be per entry file in the rollup input.

Example rollup config: https://github.com/bordoley/reactive-js/blob/72444e795a181f19752810a75d7e79b6ddec4b6c/rollup.config.js#L55-L61

Example output file that should  not include a reference to node: https://github.com/bordoley/reactive-js/blob/72444e795a181f19752810a75d7e79b6ddec4b6c/mod/functions.d.ts 

This impacts me because I'm publishing output files in .d.ts and .mjs format to github for import from deno. The node reference in files that do not depend upon node prevents deno from importing types and thus i'm having to fallback to using javascript instead of typescript in that environment.

**Comment by Swatinem** [comment]
Sorry for the delay, should be fixed in `2.0.1` now.
