### ISSUE TITLE
Is there a way to have declaration merging across multiple files?

### ISSUE THREAD

**Issue by etimberg** [Swatinem/rollup-plugin-dts#129]
# Background

Let's say that I had two types that reference each other, using declaration merging I could write this as follows.

```ts
interface A {}
interface B {}

interface A {
  prop: B;
}

interface B {
  prop: A;
}
```

## Splitting Definitions into Modules

What I'd like to achieve is having these definitions split among 3 files so that I can import the interface definitions without running into circular imports.

## a.d.ts

```ts
export default interface A {}
```

## b.d.ts

```ts
export default interface B {}
```

## index.d.ts

```ts
import A from './a';
import B from './b';

export interface A {
  prop: B;
}

export interface B {
  prop: A;
}
```

# Testing

I wrote an automated test in [a branch](https://github.com/etimberg/rollup-plugin-dts/tree/interface-merging-through-imports) which fails. The output generated by the test only includes the direct exported definition of `Foo`

```ts
interface Foo {
    prop2: string;
}
export { Foo };
```

If I swap around the export (and make the import non-default) such that the index file is now:

```ts
import { Foo } from './foo';
export { Foo } from './foo';

interface Foo {
  prop2: string;
}
```

the generated output becomes

```ts
interface Foo {
    prop1: number;
}
export { Foo };
```

**Comment by Swatinem** [comment]
I don’t think this is possible in general.
Rollup is built around the assumption that there is only ever one statement declaring a name.
Supporting declaration merging inside one file is basically just a giant hack right now by reordering the statements in one file, so those belonging to one name are contiguous.
