### ISSUE TITLE
Should the plugin suppress circular dependency warnings?

### ISSUE THREAD

**Issue by marijnh** [Swatinem/rollup-plugin-dts#131]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snippet

Any two declaration files that have a cyclic dependency in their _type_ imports.

### Error Message

Just a warning:

```
(!) Circular dependency
foo.d.ts -> bar.d.ts -> foo.d.ts
```

Since TypeScript itself is entirely fine with cyclic dependencies as long as they only concern types (and will strip out such `imports` from its output so that other tools don't even see them), it seems superfluous for this tool to be showing warnings for them. I guess that's just Rollup's native behavior kicking in. But would it be safe for the plugin to suppress such warnings by default?

**Comment by Swatinem** [comment]
> I guess that's just Rollup's native behavior kicking in.

Yes, it is.
There is a [`onwarn`](https://rollupjs.org/guide/en/#onwarn) hook that I think could be used for this.

**Comment by marijnh** [comment]
I know. The suggestion is for the plugin to do this so that not every user has to manually suppress them.
