### ISSUE TITLE
Is it possible to exclude symbols?

### ISSUE THREAD

**Issue by elalish** [Swatinem/rollup-plugin-dts#133]
This plugin seems to be generating output just fine, but what I was hoping for is to generate the `.d.ts` file representing just the public API of a decently large TS codebase. Since this is bundled into JS where private isn't really a thing, we indicate private parts of the API with Symbols which we do not export. Of course it's not *really* private, since they are accessible with GetOwnSymbols, but it's buried enough it seems to do a good job of indicating to people when they're hacking. 

The trick is, all of these symbols are included in the output of this `.d.ts` file, along with all the internal classes they refer to, effectively making the whole private API look public. Is there a way to exclude these, thereby only representing our public API? Based on the docs, this is probably a feature request. How feasible is it? A possible alternative would be to exclude all members marked `private` or `protected`, and thereby exclude all types only referenced by those members.

**Comment by Swatinem** [comment]
Well, there is https://www.typescriptlang.org/tsconfig#stripInternal otherwise just use `private`, or even the new ES private properties.
