### ISSUE TITLE
Documentation is unclear.

### ISSUE THREAD

**Issue by voorjaar** [Swatinem/rollup-plugin-dts#135]
```diff
import dts from "rollup-plugin-dts";

const config = [
  {
-   input: "./my-input/index.d.ts",
+  input: "./my-input/index.ts",
    output: [{ file: "dist/my-library.d.ts", format: "es" }],
    plugins: [dts()],
  },
];

export default config;
```
`index.d.ts` would mislead people to think that in order to bundle types file, they must first generate `index.d.ts`, but in fact we can use typescript entripoint like `index.ts`.

**Comment by Swatinem** [comment]
> `index.d.ts` would mislead people to think that in order to bundle types file, they must first generate `index.d.ts`

They definitely *should*! While jus, you *can* use the `.ts` file directly, it is a maintenance nightmare for me, and at the very least bad for compile time for the user.

I intentionally want to steer people in the direction of first generating `.d.ts` files.

**Comment by voorjaar** [comment]
For me compile time should not a problem. Because we only use this bundler for production version. While developing, we use tsc to speed up.

**Comment by Swatinem** [comment]
> While developing, we use tsc to speed up.

well yes, the idea is to use that output straight away.
