### ISSUE TITLE
Cannot be used with other rollup plugins, the configuration must be separate.

### ISSUE THREAD

**Issue by voorjaar** [Swatinem/rollup-plugin-dts#136]
#### Not works

```ts
{
    input: 'src/plugin/index.ts',
    output: [
      {
        file: dump('plugin/index.js'),
        exports: 'default',
        format: 'cjs',
      },
      {
        file: dump('plugin/index.mjs'),
        format: 'esm',
      },
      {
        file: dump('plugin/index.d.ts'),
        format: 'es',
      },
    ],
    plugins: [
      ts_plugin,
      dts(),
      resolve(),
      pack('plugin'),
    ],
},
```

#### Works

```js
{
    input: 'src/plugin/index.ts',
    output: [
      {
        file: dump('plugin/index.js'),
        exports: 'default',
        format: 'cjs',
      },
      {
        file: dump('plugin/index.mjs'),
        format: 'esm',
      },
    ],
    plugins: [
      ts_plugin,
      resolve(),
      pack('plugin'),
    ],
},
{
    input: 'src/plugin/index.ts',
    output: [
     {
        file: dump('plugin/index.d.ts'),
        format: 'es',
      },
    ]
    plugins: [
        dts(),
    ]
}
```

### Error Message

Generated `index.js` and `index.mjs` will be overwited by `index.d.ts`.

**Comment by Swatinem** [comment]
Hm, the plugin can’t be combined with other transformation plugins, and might conflict with any resolvers. How should I improve the docs to make this clear?

**Comment by voorjaar** [comment]
Sorry about this.

**Comment by voorjaar** [comment]
> Hm, the plugin can’t be combined with other transformation plugins, and might conflict with any resolvers. How should I improve the docs to make this clear?

But why not just solve this problem, but get rid of it? I don't think this is an unsolvable problem, of course I maybe wrong.

**Comment by Swatinem** [comment]
The plugin fundamentally works by transforming type definitions. You put type definitions into the pipeline, and get those out.
