### ISSUE TITLE
Feature request: Allow passing in a readFile function as an option

### ISSUE THREAD

**Issue by marijnh** [Swatinem/rollup-plugin-dts#137]
I have a setup where I'm using this plugin as part of a build pipeline that doesn't write its intermediate files to disk. I'm currently doing a dodgy thing where I temporarily overwrite `ts.sys.readFile` to hook in access to the files I have in memory, and it works, but I'd like to not do that. I'll gladly prepare a PR if this is something you'd be open to.

**Comment by Swatinem** [comment]
I think that is a sensible thing to do, yes.

I wanted to revamp the loading/transforming parts of this plugin at some point either way, but I don’t think I will have time for that anytime soon.

So this would override the `readFile` hook that is being passed to the `createProgram` calls as well, right?

**Comment by marijnh** [comment]
Yes, that'd be the idea.

Another possible approach, which would be cleaner and also serve my purpose, would be to replace the plugin's `load` hook with a `transform` hook... but I'm guessing there is a reason it's a `load` hook?

**Comment by Swatinem** [comment]
I have to double-check, this was all quite long ago, but back then I think I had to use the `load` hook to avoid the code being parsed as JS.

**Comment by marijnh** [comment]
The [docs](https://rollupjs.org/guide/en/#transform) suggest it runs before parsing (which makes sense because most types of transformation plugins will need to act before parsing).

**Comment by marijnh** [comment]
(If you don't have time, but are open to the change, I can take a stab at moving this to a transform hook, and let you know if it's possible.)

**Comment by Swatinem** [comment]
Sure, that would be awesome!

BTW, my reasoning why I was looking into having both load+transform hooks was to better support sourcemaps:
* `load` the `.d.ts{,.map}`
* `transform` and return another `map` via `magic-string` which I started using in the preprocessor.
* (eventually use `magic-string` again in the post-processor to have sourcemaps front to back)

**Comment by marijnh** [comment]
Thanks a lot! If you have the time to cut a release in the near future, I'll glad to be able to drop my hack.

**Comment by Swatinem** [comment]
> If you have the time to cut a release in the near future, I'll glad to be able to drop my hack.

Published `3.0.0`; major bump since I used the opportunity to switch to ES modules and drop Node 10 support.

**Comment by marijnh** [comment]
Appreciated.
