### ISSUE TITLE
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead

### ISSUE THREAD

**Issue by microshine** [Swatinem/rollup-plugin-dts#14]
I'm not sue is it rollup or plugin error. I'm trying to build this [project](https://github.com/PeculiarVentures/webcrypto-local/tree/lerna) with your plugin. It works fine for TS. But I've got Error for DTS.

The error occurs if namespace is using for class implementation
![image](https://user-images.githubusercontent.com/7333669/54716239-5e28f280-4b66-11e9-8749-1bbccbfe092f.png)

It works fine if interface is using without namespace
![image](https://user-images.githubusercontent.com/7333669/54716915-fa9fc480-4b67-11e9-8958-4989e2673aeb.png)

### Error
```
src/index.ts → build/index.d.ts...
[!] Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.overwrite (node_modules/rollup/dist/rollup.js:1443:33)
```

**Comment by microshine** [comment]
The same Error for `extends`

```ts
import * as some from "module"

export class TestClass extends some.ParentClass {
}
```

**Comment by prisis** [comment]
Have the same error, if I'm not wrong namespaces are not supported right now

**Comment by Swatinem** [comment]
The namespace limitation is about *exporting* namespaces.

This usecase should actually work. I will take a look once I find some time.

**Comment by Swatinem** [comment]
Thanks for the report. I published `v0.14.0` with the fix, please try that :-)

**Comment by prisis** [comment]
That was fast, I will try it out, was always thing that this was a limitation

**Comment by Swatinem** [comment]
> was always thing that this was a limitation

The limitations around namespaces are documented in https://github.com/Swatinem/rollup-plugin-dts/issues/7
