### ISSUE TITLE
Broken sourcemap

### ISSUE THREAD

**Issue by Mister-Hope** [Swatinem/rollup-plugin-dts#142]
```
./src/index.ts → node/index.d.ts...
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'dts') should generate accompanying sourcemaps
created node/index.d.ts in 1.6s
```
I was previously running on `2.0.1` and ts@4.1 when the sourcemap works fine. After I upgrade to `3.0.1` and ts@4.2.3, I am getting the above error.

Is there any thing I should change upgrading to V3? I am not seeing those in changelog. Thanks.

```js
  {
    input: "./src/index.ts",
    output: [{ file: pkg.types, format: "esm", sourcemap: true }],
    plugins: [dts()],
  },
```

**Comment by Mister-Hope** [comment]
Sorry I downgrade to the old deps again, and I am still getting empty sourmaps.

It seems that this warning is added by a recent rollup version.

So this plugin is not supporting sourcemap right?

**Comment by Swatinem** [comment]
> So this plugin is not supporting sourcemap right?

No, it never really has. Maybe the switch from `load` hook to `transform` has surfaced this error now.
