### ISSUE TITLE
Doesn't work with pnpm (tested with Vue 3)

### ISSUE THREAD

**Issue by egoist** [Swatinem/rollup-plugin-dts#143]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

`index.ts`:

```ts
export { App } from "vue"
```

`rollup.config.js`:

```js
import dts from "rollup-plugin-dts"

export default {
  input: "./index.ts",
  output: {
    format: "esm",
    file: "out.d.ts",
  },
  plugins: [dts()],
}
```

`package.json`:

```json
{
  "private": true,
  "dependencies": {
    "rollup": "^2.43.0",
    "rollup-plugin-dts": "^3.0.1",
    "typescript": "^4.2.3",
    "vue": "^3.0.8"
  }
}
```

Run `pnpm i` to install dependencies.

### Error Message

```
❯ ./node_modules/.bin/rollup -c

./index.ts → out.d.ts...
index.ts(1,10): error TS2305: Module '"vue"' has no exported member 'App'.

[!] (plugin dts) Error: Failed to compile. Check the logs above.
index.ts
Error: Failed to compile. Check the logs above.
```

Seems it's related to:

https://github.com/Swatinem/rollup-plugin-dts/blob/7ae48c8c579ae73d8cc95042661d0f9151207679/src/program.ts#L25

It works after I changed this to `false`.

**Comment by Swatinem** [comment]
So this is not an issue when using npm or yarn (that don’t use symlinks)?

CC @aleclarson as you added this in https://github.com/Swatinem/rollup-plugin-dts/commit/afbfb54f64652e3b89434bd8247372b126afc1db

These types of problems are exactly the reason why I discourage people from using `.ts` files. Is there a specific reason you do so instead of pre-compiling to `.d.ts`?

Either way, if that flag is the only thing thats needed for the fix, and if its passing all the other tests fine, I guess we can toggle it off.

**Comment by egoist** [comment]
> So this is not an issue when using npm or yarn (that don’t use symlinks)?

yes.

> Is there a specific reason you do so instead of pre-compiling to .d.ts?

Same as that PR, to avoid an extra step

**Comment by vvni** [comment]
me too..

**Comment by aleclarson** [comment]
I'm using this feature with pnpm, no problem.

Here's my rollup config:
```js
import dts from 'rollup-plugin-dts'
import esbuild from 'rollup-plugin-esbuild'

const name = require('./package.json').main.replace(/\.js$/, '')

const ext = format =>
  format == 'dts' ? 'd.ts' : format == 'cjs' ? 'js' : 'mjs'

const bundle = format => ({
  input: 'src/index.ts',
  output: {
    file: `${name}.${ext(format)}`,
    format: format == 'cjs' ? 'cjs' : 'es',
    sourcemap: format != 'dts',
  },
  plugins: format == 'dts' ? [dts()] : [esbuild()],
  external: id => !/^[./]/.test(id),
})

export default [
  bundle('es'), //
  bundle('cjs'),
  bundle('dts'),
]
```

**Comment by egoist** [comment]
@aleclarson can you test it with Vue 3 types? I tried but it still doesn't work. Or we can just remove `preserveSymlinks: true` if it's not necessary.

**Comment by aleclarson** [comment]
Do you have a test repo? I don't use Vue.

> Or we can just remove `preserveSymlinks: true` if it's not necessary.

As the code comment says, it's there so TS2742 errors are visible.

https://github.com/Swatinem/rollup-plugin-dts/blob/7ae48c8c579ae73d8cc95042661d0f9151207679/src/program.ts#L24-L25

**Comment by kx59717** [comment]
same issue!

**Comment by JobinJIa** [comment]
I think I should be in the same trouble.
Here's my log
![image](https://user-images.githubusercontent.com/9244703/139660790-f759a274-721a-4fa7-b6dc-11981f89fbf4.png)

when i add `dts()` in rollup.config.js plugins option
```
// rollup.config.js
import dts from 'rollup-plugin-dts'
export default {
  plugins: {dts()}
}
```

**Comment by egoist** [comment]
@PuruVJ you can now add `preserveSymlinks: false` in tsconfig.json to override this

**Comment by PuruVJ** [comment]
Thanks! Works like a charm

**Comment by LiuJinYang9527** [comment]
Adding `preserveSymlinks: false` to tsconfig.json doesn't work for me,  HERE's how I resolved it:
```js
import dts from 'rollup-plugin-dts'
 // rollup.config.js
plugins: [
  dts({
   compilerOptions: {
      preserveSymlinks: false
    }
  })
]
```

**Comment by BTBMan** [comment]
Great! `preserveSymlinks: false` It's work for me

**Comment by TuiMao233** [comment]
`compilerOptions: {preserveSymlinks: false}` on the mac is of no use to me.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/49724027/221758792-78125f84-d298-4696-90d4-1ab90d4a6091.png">

**Comment by wuchanghuan1995** [comment]
Thanks `preserveSymlinks: false `  It works for my project,

**Comment by by1773** [comment]
Great! preserveSymlinks: false It's work for me    Thanks
