### ISSUE TITLE
Could not resolve './index'

### ISSUE THREAD

**Issue by klevron** [Swatinem/rollup-plugin-dts#146]
Hi, I'm trying to bundle .d.ts files from a project but I get the following error :

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

`types/export.d.ts` :

```ts
export * from './index';
```

### Error Message

```
[!] Error: Could not resolve './index' from types\export.d.ts
Error: Could not resolve './index' from types\export.d.ts
    at error (F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:5305:30)
    at ModuleLoader.handleResolveId (F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:18531:24)
    at F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:18487:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:18485:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:18461:9)
    at async Promise.all (index 0)
```

### Rollup config
```
  {
    input: 'types/export.d.ts',
    output: {
      format: 'es',
      file: 'build/trois.d.ts',
      plugins: [dts()],
    },
  }
```

**Comment by Swatinem** [comment]
does this work correctly if you just add a file extension there?

**Comment by klevron** [comment]
No, strange, same error : `[!] Error: Could not resolve './index.ts' from types\export.d.ts`

**Comment by klevron** [comment]
Sorry...

**Comment by klevron** [comment]
It's me again, sorry I don't understand how to bundle only my d.ts files.
With the example above : `export * from './index'` will export `./index.js` and not `./index..d.ts`
I think I miss something

**Comment by Swatinem** [comment]
I have quite little to go on here, how does your project look like? is it open source somewhere?

**Comment by klevron** [comment]
Yes, I made a branch : https://github.com/troisjs/trois/tree/rollup-plugin-dts
There's a "yarn types" command to call tsc, and "yarn rollup".

I first have the following error :
```
[!] (plugin dts) TypeError: Cannot destructure property 'type' of 'itemTypes[localName]' as it is undefined.
TypeError: Cannot destructure property 'type' of 'itemTypes[localName]' as it is undefined.
    at NamespaceFixer.fix (F:\DEV\TroisJS\trois\node_modules\rollup-plugin-dts\dist\rollup-plugin-dts.cjs:179:29)
    at Object.renderChunk (F:\DEV\TroisJS\trois\node_modules\rollup-plugin-dts\dist\rollup-plugin-dts.cjs:1468:27)
    at F:\DEV\TroisJS\trois\node_modules\rollup\dist\shared\rollup.js:18780:25
```

I modified `rollup-plugin-dts.cjs` to avoid this error, it works but it bundles js code instead of d.ts.

**Comment by Swatinem** [comment]
Ah yes, rollup prints the following error:

```
(!) The "options" hook used by the output plugin dts is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "resolveId" hook used by the output plugin dts is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
(!) The "transform" hook used by the output plugin dts is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
```

Because you have the `plugin` line inside of the output. it has to be on the toplevel, then it will work, like this:

```
{
    input: "types/export.d.ts",
    external,
    plugins: [dts()],
    output: {
      format: "es",
      file: "build/trois.d.ts",
    },
  },
```

**Comment by klevron** [comment]
Omg, sorry I feel stupid, I think I was tired yesterday evening... But I don't understand why I didn't get those error messages.

Thanks a lot for taking time to look at this.
