### ISSUE TITLE
Generated type definition file is empty

### ISSUE THREAD

**Issue by vegidio** [Swatinem/rollup-plugin-dts#147]
### Checklist

* [X] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [X] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [X] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
import commonjs from '@rollup/plugin-commonjs';
import typescript from 'rollup-plugin-typescript2';
import dts from 'rollup-plugin-dts';

export default [
    {
        input: 'src/index.ts',
        plugins: [commonjs(), typescript({ useTsconfigDeclarationDir: true })],
        output: [
            {
                file: 'dist/bundle.js',
                format: 'esm',
                sourcemap: false,
            },
        ],
    },
    {
        input: 'dist/types/index.d.ts',
        output: [{ file: 'dist/types.d.ts' }],
        plugins: [dts()],
    },
];

```

### Error Message

I created a simple project (it can be found here: https://github.com/vegidio-js/template-typescript) where I'm trying to put all the type definition files created by TypeScript into a single `d.ts` file, but the generated `d.ts` file is blank.

If you clone the project above and run `yarn && yarn build` then you will see the following message:

```
dist/types/index.d.ts → dist/types.d.ts...
(!) Generated an empty chunk
index.d
created dist/types.d.ts in 7ms
```

This seems to be happening because my `d.ts` entrypoint `dist/types/index.d.ts` is blank, but all the other `d.ts` files generated by TS have something in it, but isn't this package supposed to merge all files together under a single one or did I miss something in the configuration?

**Comment by Swatinem** [comment]
> This seems to be happening because my `d.ts` entrypoint `dist/types/index.d.ts` is blank

I think thats because https://github.com/vegidio-js/template-typescript/blob/master/src/index.ts has no `export` declarations in it. Typescript will do its own dead code elimination. And obviously if your index file is empty, this plugin won’t find anything.

**Comment by vegidio** [comment]
Damn, such a silly mistake of mine 🙈
Sorry for wasting your time on this.

**Comment by IanVS** [comment]
Typescript itself will generate a declaration file with `export {}` even if there are no exports in the source file.  See https://github.com/microsoft/TypeScript/issues/20496.

**Comment by await-ovo** [comment]
Although typescript emitted `export {}` in declaration file, It seems that rollup itself will convert `export {}` to empty string.
Can we  add `export { }` directly to the generated emty code to avoid empty dts file:

```
const plugin = () => ({
  renderChunk: (code) => {
    if (!code) {
      code += 'export { }'
    }
    return code
  }
})
```
