### ISSUE TITLE
Plugin interferes with Rollup watch

### ISSUE THREAD

**Issue by robhicks** [Swatinem/rollup-plugin-dts#15]
I tried the plugin over the weekend. It works well except I cannot get rollup watch to work with it.  

Please let me know what I'm doing wrong: 
https://bitbucket.org/robhicks55/rollup-plugin-dts-watch/src/master/

**Comment by Swatinem** [comment]
I don’t think you are doing anything wrong, rather the plugin is fundamentally incompatible with `rollup-watch`.
I basically use the TS compiler internally, which itself compiles/typechecks the whole project at once. Making it work with a watcher would probably involve some work inside the plugin.

**Comment by Swatinem** [comment]
`1.0.0-alpha.0` should work. at least it does not do any internal caching itself.
