### ISSUE TITLE
Duplicate ".d" at the end of filename when using "preserveModules"

### ISSUE THREAD

**Issue by guilhermetod** [Swatinem/rollup-plugin-dts#152]
Hey there, I really like this plugin and use it most of the time to bundle all my typings. However, in some larger project, I prefer to keep the folder structure and generate cjs, mjs and types folder with preserveModules: true, so I also use this plugin as a workaround for the fact that the official typescript plugin will ignore the "emitDeclarationOnly" flag.

But I recently noticed a small bug when generating the types: the ".d.ts" files that are corresponding to src ".d.ts" get an extra ".d" in their extension.

### Checklist

* [ X ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ X ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ X ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snippet

[I created a repo to show the problem](/guilhermetod/dts-bug)

To reproduce the bug, simply clone the project, install the dependencies and them run `npm run build`.

Then, check the dist folder and you'll see that the "src/definition.d.ts" file got output ad "dist/definition.d.d.ts"

This is a really small bug, but I thought it would be nice to report it. I took a quick look but I'm not sure where this is generated. If anyone can point me out in a closer direction, I can create a PR to fix this.

**Comment by Swatinem** [comment]
I think you can pass a function to https://rollupjs.org/guide/en/#outputentryfilenames to filter these out.

https://github.com/Swatinem/rollup-plugin-dts/blob/f9a102d5b2e90fd677f571b6b852c7a7dda87418/src/transform/index.ts#L62-L63

This is where I just blindly slap `.d.ts` on the file name.

**Comment by eddiemonge** [comment]
Its also duplicated if you specify folder instead of filename
