### ISSUE TITLE
Imports without an extension ('./my-class') silently ignored

### ISSUE THREAD

**Issue by donmccurdy** [Swatinem/rollup-plugin-dts#153]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
* [x] This issue is not related to rolling up `@types`.

### Code Snipped

```
yarn add @gltf-transform/core @gltf-transform/extensions @gltf-transform/functions
```

```ts
import dts from 'rollup-plugin-dts';

const config = [
	{
		input: './node_modules/@gltf-transform/core/dist/core.d.ts',
		output: [{file: 'types/gltf_transform_core.d.ts', format: 'es'}],
		plugins: [dts()],
	},
	{
		input: './node_modules/@gltf-transform/extensions/dist/extensions.d.ts',
		output: [{file: 'types/gltf_transform_extensions.d.ts', format: 'es'}],
		plugins: [dts()],
	},
	{
		input: './node_modules/@gltf-transform/functions/dist/index.d.ts',
		output: [{file: 'types/gltf_transform_functions.d.ts', format: 'es'}],
		plugins: [dts()],
	},
];

export default config;
```

### Error Message

No error is shown, but the types are not actually rolled up. Instead, the output leaves all relative imports untouched:

```ts
import { Extension } from './extension';
export { Extension } from './extension';
...
```

I can work around the issue by adding ".ts" extensions to every import throughout my project, and things are bundled correctly. But it seems that TypeScript [actively discourages](https://github.com/Microsoft/TypeScript/issues/27481) explicit extensions on imports, so I'm hoping there's another way to do this. Thanks!

**Comment by donmccurdy** [comment]
Clarification: I tested adding explicit `*.d.ts` extensions to the type definitions generated by TypeScript, which seems to work around the issue, but there are a lot of imports to edit this way. :) I haven't tested whether changing the imports in the source code (`*.ts`) before compiling with TypeScript would result in type definitions that explicitly import `*.d.ts` extensions.

**Comment by Swatinem** [comment]
One thing that caught my eye is that you are trying to explicitly bundle up things from `node_modules`.
Typescript flags those as external, maybe that is the source of the problem.

https://github.com/Swatinem/rollup-plugin-dts/blob/f9a102d5b2e90fd677f571b6b852c7a7dda87418/src/index.ts#L132-L139

Can you try running with `respectExternal`?

**Comment by donmccurdy** [comment]
Thanks! Running with `dts({respectExternal: true})` does inline all of the type definitions, but also (as expected) inlines the type definitions of dependencies, which creates a new problem.

It's helpful to know that bundling things located in `node_modules/` was the issue though — if I copy the dependencies out of that folder, and then bundle, things appear to be working just fine. 🙂

**Comment by Swatinem** [comment]
nice! IMO, you shouldn’t bundle up types from `node_modules`, but only your own.

**Comment by donmccurdy** [comment]
I'm trying to configure a web-based tool using the Monaco Editor (https://microsoft.github.io/monaco-editor/) to have type definitions (and autocomplete) for several existing npm packages. As far as I can tell, Monaco requires that each package's type definitions be concatenated into a single file (https://github.com/microsoft/monaco-editor/issues/1839), and anyway that's much more practical for loading on the web. So I needed to repackage the already-published type definitions. 

Copying the packages out of `node_modules` (where they're installed by my tool) is easy enough as a workaround though!

**Comment by Swatinem** [comment]
Ah okay, that makes sense. I mean ideally those things should be bundled upstream, but meh, there is lots of catch up to do to convince other devs to take advantage of bundling.
