### ISSUE TITLE
Export all interfaces and declarations

### ISSUE THREAD

**Issue by ritz078** [Swatinem/rollup-plugin-dts#155]
Is it possible to export all the internal interfaces too ? I couldn't find any option for that. If you are shipping a library, this becomes very important.

**Comment by Swatinem** [comment]
I think you can use the [`treeshake`](https://rollupjs.org/guide/en/#treeshake) option for that, but I don’t really understand your usecase why you would want to do that?

**Comment by ritz078** [comment]
> I think you can use the treeshake option for that

I do not want to disable treeshaking. I want all the internal types that land up in the bundled declarations file to be exported.

For eg:

```ts
interface Milestone {
  a: string;
}
const x: Milestone = { a: "hello" };

export default x
```

should end up as:

```ts
export interface Milestone { // <= I want this to be exported too.
    a: string;
}
declare const x: Milestone;
export default x;
```

Right now the resulting declarations are:

```ts
interface Milestone {
    a: string;
}
declare const x: Milestone;
export default x;
```

What I want is that, even `MileStone` interface is exported. I want all the declarations to be exported and not only the one that was originally exported so that the users and import and use them.

**Comment by Swatinem** [comment]
I mean… then just export them as normal. I mean thats the whole point of rollup that it has the exact same exports that you specify.

**Comment by rafa-thayto** [comment]
I had the same issue

**Comment by isonlaxman** [comment]
did you have any luck with this? @ritz078
