### ISSUE TITLE
Emitting code that errors with TS1254

### ISSUE THREAD

**Issue by jonahsnider** [Swatinem/rollup-plugin-dts#158]
### Checklist

* [ ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

Seems to be coming from improper generation of an object exported `as const`.
If needed I can try making an actual reproduction but I think this is enough.

Does something like this

```ts
declare const obj = {
	"prop": [0, 1, 2]
} as const;
```

Should be imitating `tsc`:

```ts
declare const obj: {
	readonly prop: readonly [0, 1, 2];
}
```

### Error Message

```
error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
```

**Comment by Swatinem** [comment]
I don’t fully understand what the source here is, and what `tsc` emits as its own `.d.ts` definition for that.

**Comment by jonahsnider** [comment]
Appears to no longer be an issue, must have been silently fixed earlier
