### ISSUE TITLE
global namespace is not work

### ISSUE THREAD

**Issue by janryWang** [Swatinem/rollup-plugin-dts#160]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
import * as Types from './types'
import * as Models from './models'

declare global {
  namespace Named.Core {
    export { Types, Models }
  }
}

```

### Error Message

```
// The Error Message thrown by rollup / the plugin.
[!] (plugin dts) Error: namespace must have a "ModuleBlock" body.
```

**Comment by janryWang** [comment]
I found it worked when I change Named.Core to NamedCore, but why?

**Comment by janryWang** [comment]
https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/transform/DeclarationScope.ts#L322
this code , the node may be a ModuleDeclaration

**Comment by Swatinem** [comment]
I think there might be some weird cases where rollup will miss renaming some identifiers, but I think the code in https://github.com/Swatinem/rollup-plugin-dts/pull/164 should at least get your use case working.

**Comment by janryWang** [comment]
thanks
