### ISSUE TITLE
export type not working as expected

### ISSUE THREAD

**Issue by ritz078** [Swatinem/rollup-plugin-dts#161]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
declare class Instance {
}

export type { Instance };
```

### Error Message

The output I get from rollup-plugin-dts doesn't include `type`

```ts
declare class Instance {
}

export { Instance };
```

If we run the same code on the TypeScript playground, `type` exists: https://www.typescriptlang.org/play?#code/MYGwhgzhAECSB2EAuZ7AKbQN4FgBQ+AvvvugB4AOA9gE5LRICeFmWciKamhQA

**Comment by Swatinem** [comment]
This is expected. Rollup generated these export declarations, so there is no `type`. Also by definition, `.d.ts` files export only types.

**Comment by ritz078** [comment]
> Also by definition, .d.ts files export only types.

Yes, it does export types only but while importing the proper error message is not given. If we generate .d.ts using TypeScript, the `type` info [is present there](https://www.typescriptlang.org/play?#code/MYGwhgzhAECSB2EAuZ7AKbQN4FgBQ+AvvvugB4AOA9gE5LRICeFmWciKamhQA). This allows proper error message if someone imports the type and uses it as a value.

**Comment by Swatinem** [comment]
I understand. I still think this is not something that is technically fixable at the moment.
