### ISSUE TITLE
Using `rollup-plugin-styles`: Couldn't resolve .css files

### ISSUE THREAD

**Issue by baptisteArno** [Swatinem/rollup-plugin-dts#165]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Issue

I'm using `rollup-plugin-styles` to allow css imports. But it isn't compatible with `rollup-plugin-dts`. How can I make this work?

### Rollup config

```
import typescript from "@rollup/plugin-typescript";
import { terser } from "rollup-plugin-terser";
import styles from "rollup-plugin-styles";
import dts from "rollup-plugin-dts";

export default [
  // ES Modules
  {
    input: "src/index.ts",
    output: {
      file: "dist/index.es.js",
      format: "es",
    },
    plugins: [typescript({ tsconfig: "./tsconfig.json" }), styles()],
  },

  // UMD
  {
    input: "src/index.ts",
    output: {
      file: "dist/index.umd.min.js",
      format: "umd",
      name: "reactUseThrottle",
      indent: false,
    },
    plugins: [typescript({ tsconfig: "./tsconfig.json" }), terser(), styles()],
  },

  // Types
  {
    input: "dist/types/index.d.ts",
    output: {
      file: "dist/dts/index.d.ts",
      format: "es",
    },
    plugins: [dts(), styles()],
  },
];

```

### Error Message

```
Error: Could not resolve './style.css' from dist/types/embedTypes/chat/index.d.ts
    at error (/Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:151:30)
    at ModuleLoader.handleResolveId (/Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:19841:24)
    at /Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:19790:22
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (/Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:19788:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:19764:9)
    at async Promise.all (index 2)
    at ModuleLoader.fetchStaticDependencies (/Users/baptistearnaud/Dev/typebot-io/typebot-js/node_modules/rollup/dist/shared/rollup.js:19788:34)
    at async Promise.all (index 0)
```

**Comment by Olli-palkkaus** [comment]
We have the same issue with less files that are included / imported in TypeScript.

Untill this is fixed, we were able to bypass it by adding the file in externals (path is realtive to input file):

```
external: [ 
    "../less/salaxy-reports.less" // HACK: Fix for this problem https://github.com/Swatinem/rollup-plugin-dts/issues/165
]
```

For us, this was quite easy as we only have this one less file and it then imports others. This hack may be considerably more difficult in cases where you have a lot of components/pages and you have one less/sass/css per each item.

**Comment by Swatinem** [comment]
Combining this plugin with other plugins that are not really typescript-aware is not really possible.

My question is, why is this turning up in the export chain, and is not being eliminated?

**Comment by axelboc** [comment]
> My question is, why is this turning up in the export chain, and is not being eliminated?

I'm using Vite in library mode to generate JS bundles in my project, and then `tsc` to generate the declaration files. Vite processes the CSS imports as expected by generating a CSS bundle, but `tsc` just leaves them as they are (probably because of the `declare module "*.css" { ... }` typing that Vite provides to make TS happy).

The result is that the declaration files generated by `tsc` contain CSS imports, which this plugin cannot resolve. Any clue how to work around this (apart from removing the CSS imports as part of an intermediary step between `tsc` and running Rollup with this plugin, which would not be very practical)?

**Comment by axelboc** [comment]
Got it, just had to add `external: [/\.css$/u]` to the Rollup config.

**Comment by Swatinem** [comment]
I think another option would be to write a custom resolver/loader plugin which just returns the equivalent snippet to the `module "*.css"` above.
