### ISSUE TITLE
Does not merge local module declarations

### ISSUE THREAD

**Issue by RebeccaStevens** [Swatinem/rollup-plugin-dts#168]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
// index.d.ts
export * from "./file1";
export * from "./file2";
```

```ts
// file1.d.ts
export interface Foo {
  prop1: number;
  prop2: number;
}

export type Bar = {
  prop1: string;
  prop2: string;
}
```

```ts
// file2.d.ts
import type { Bar } from "./file1";

declare module "./file1" {
  interface Foo {
    prop3: number;
    prop4: string;
  }
}

export type Baz = Bar & {
  prop3: string;
  prop4: string;
}
```

### Actual Output

```ts
interface Foo {
  prop1: number;
  prop2: number;
}

type Bar = {
  prop1: string;
  prop2: string;
}

declare module "./file1" {
  interface Foo {
    prop3: number;
    prop4: string;
  }
}

type Baz = Bar & {
  prop3: string;
  prop4: string;
}

export { Bar, Baz, Foo };
```

### Expected Output

```ts
interface Foo {
  prop1: number;
  prop2: number;
}

type Bar = {
  prop1: string;
  prop2: string;
}

interface Foo {
  prop3: number;
  prop4: string;
}

type Baz = Bar & {
  prop3: string;
  prop4: string;
}

export { Bar, Baz, Foo };
```

<details>
<summary><strong>Or even better</strong></summary>

```ts
interface Foo {
  prop1: number;
  prop2: number;
  prop3: number;
  prop4: string;
}

type Bar = {
  prop1: string;
  prop2: string;
}

type Baz = Bar & {
  prop3: string;
  prop4: string;
}

export { Bar, Baz, Foo };
```

</details>

**Comment by Swatinem** [comment]
I agree that it would be nice if all of the different places where you could declare things would be merged into a single declaration.

However this plugin only works on a file-by-file basis, and being based on rollup, I don’t think its possible to just create a "virtual file" from within another one (the module declaration) which also has the same name as an actual existing file.

Long story short, I don’t think this is possible at all with the current architecture. I also don’t think this is particularly desirable, as you should just declare your types in one place.

**Comment by RebeccaStevens** [comment]
> as you should just declare your types in one place

Normally yes but there is 1 pattern I know of where defining them in separate places makes sense. That pattern being when you are working with High-Kinded Types following the same pattern "fp-ts" uses (without actually using `fp-ts`). To define them all in one place means would have to put all HKTs in the same file even if these types have no relevance to each other at all.

**Comment by Swatinem** [comment]
But in that case you can import that type, and extend it then. But TBH I haven’t tried that.
