### ISSUE TITLE
Unresolved dependencies when using paths.

### ISSUE THREAD

**Issue by RebeccaStevens** [Swatinem/rollup-plugin-dts#169]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
// index.ts
export * from "@/foo";
```

```ts
// some-other-file.ts
export interface Foo {
  prop1: number;
  prop2: number;
}
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/foo": ["some-other-file.ts"]
    }
  }
}
```

### Error Message

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@/foo (imported by index.ts)
```

### Workaround

Also use plugin `@rollup/plugin-typescript`.

**Comment by Swatinem** [comment]
I think your proposed workaround is a reasonable approach.
Path mapping is not supported right now. The way to do it is to manually re-create the path mappings for rollup, or to use another plugin that does so.

**Comment by RebeccaStevens** [comment]
[tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) tends to be what other packages use for this purpose.

**Comment by tvolodimir** [comment]
found a workaround
```ts
import ts from 'typescript';
...
      plugins: [
        dts({
          compilerOptions: {
            baseUrl: rootFolderPathWithDTSFiles,
            paths: ts.readConfigFile(tsConfigPath, p => readFileSync(p, 'utf8')).config.paths,
          },
        }),
      ],
...
```

**Comment by Thremulant** [comment]
Solved this issue by using [rollup-plugin-tsconfig-paths](https://www.npmjs.com/package/rollup-plugin-tsconfig-paths), it removed the warnings, and resolved the paths correctly. 

````javascript
import tsConfigPaths from "rollup-plugin-tsconfig-paths"
...
{
    ...,
    plugins: [
        peerDepsExternal(), 
        nodeResolve(), 
        tsConfigPaths(), 
        dts()
    ],
}

````

**Comment by ovanderzee** [comment]
With typescript 4.9., rollup 3.10 and dts 0.1.1, I did not get a warning but I got a d.ts file with an import pointing to my @src/types.ts file. 
Also not usable.
I could have lived with relative paths, but rollup-plugin-tsconfig-paths helped me.
