### ISSUE TITLE
Cannot read property 'module' of null

### ISSUE THREAD

**Issue by aleclarson** [Swatinem/rollup-plugin-dts#171]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Description

Exporting a `declare global` variable from a module results in an error when imported by another module.

**main.ts**
```ts
import {Foo} from './types'

const api = {
  foo(foo: Foo) {},
}

export default api
```

**types.d.ts**
```ts
declare global {
  interface Foo {
    foo: string
  }
}

export { Foo }
```

This isn't a big deal, as it's not really an idiomatic use case, and the workaround is easy (just use the global, don't import it). The reason I was exporting the global is that there was a bug in `rollup-plugin-dts@1.4`, but upgrading seems to have fixed it.

### Reproduction

See the readme: https://github.com/aleclarson/repro/tree/dts-8-31-2021

**Comment by Swatinem** [comment]
This is an interesting case. I think the plugin is just too "stupid" in that case, it just walks the AST and converts it, and it does not look inside the global declaration at all.
So it ends up handing an invalid export (of something that does not exist) to rollup, which then trips up on that.
