### ISSUE TITLE
[Feature Request] Clean up/delete bundled types

### ISSUE THREAD

**Issue by fgblomqvist** [Swatinem/rollup-plugin-dts#175]
This plugin works great so far, but I noticed in the output dir that all the individual type files remain. E.g. I get a merged index.d.ts but still have all the Button.d.ts, Header.d.ts files. Is it possible to tell this plugin to "clean up" as well? Perhaps that would be a good feature (e.g. a flag) to add?

**Comment by Swatinem** [comment]
This is not something the plugin would do (neither does any other rollup transform plugin AFAIK).

You could probably combine this with a different rollup plugin that does so.
