### ISSUE TITLE
Pin typescript to ~ not ^

### ISSUE THREAD

**Issue by j-m** [Swatinem/rollup-plugin-dts#176]
Typescript, surprisingly doesn't follow semver (https://github.com/microsoft/TypeScript/issues/14116) but `npm`'s `~` accuracy follows their policy of non-breaking patch (equivalent) changes.

I see that `dependency` is save exact, which makes sense, but I think `peerDependency` should be `~` not `^`. So for this package to follow semver, I'd anticipate a breaking change with each minor bump of typescript. 

I have several dependencies which are pinned to typescript's 4.1, so I'm not sure which version of this package I can use (go through git blame, I think 2.0.1?); I'd greatly appreciate release notes, especially for major releases

Thanks for your work!

**Comment by Swatinem** [comment]
I fully understand your concern, and agree that `~` would be a better SemVer range.
As for the requirements of the plugin, I think it goes a lot lower than the `peerDependency` version advertized. The TS API only breaks very infrequently.
However, I do frequent bumps. And testing against multiple TS versions is not really feasible since I rely on snapshot testing, and those snapshots could also change at any point between TS versions. So it is more a convenience to easy my own CI/testing setup.

**Comment by j-m** [comment]
Makes sense. 

Unfortunately npm 7 installs dependencies in a much stricter manner; the only way to force this package to resolve to my "incompatible" version of typescript is to use `--force` - which disables all restrictions, not just the resolutions of this 1 dependency.

So three options, 

First, I'm not sure will work, but try reducing the minor: `"typescript": "^4.0"`

Or support multiple typescript versions: `"typescript": "~4.1 || ~4.2 || ~4.3 || ~4.4"`

Or, and I fully empathise with supporting just one version of typescript, change the peerDep to `~` now and forget about previous releases; then when typescript minor bumps, you major bump. Then you only ever support 1 minor version of typescript at a time.

Of course I'd love it if you could release with ~4.1, but understand if you choose not to, e.g.

|rollup-plugin-dts|typescript|note|
|---|---|---|
|^9|~4.4| some major bump from rollup-plugin-dts, not typescript minor bump|
|^8|~4.4| typescript minor bump |
|^7|~4.3| typescript minor bump |
|^6|~4.2| typescript minor bump |
|^5|~4.1| next release, pin typescript to minor |
|^4|^4.4| latest |
|^3|^4.2| I think, just a guess |
|^2|^4.1| I think, just a guess |

Lots of "breaking" major releases! But that's semver I guess...

**Comment by j-m** [comment]
Thank you!
