### ISSUE TITLE
Rollup fails if I import a json file

### ISSUE THREAD

**Issue by HarelM** [Swatinem/rollup-plugin-dts#184]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
import v8 from './reference/v8.json';
```

### Error Message

```
[!] Error: Could not resolve './reference/v8.json' from types/src/style-spec/style-spec.d.ts
```

The long story:
I've recently migrated a javascript library written in flow to typescript.
This library had a definition file before the typescript migration and everything worked fine:
https://github.com/maplibre/maplibre-gl-js/blob/cb3a4200bfbc113969e9dcbedae2aa7655f9aa98/src/index.d.ts
After the typescript migration I saw that the generated `d.ts` file are not producing the same output (not even remotely close).
I saw that this rollup plugin might help me with my task of creating a single d.ts file generated from the typescript code, but I'm not sure how easy this will be as the typescript code is a bit complicated.
The code can be found here:
https://github.com/maplibre/maplibre-gl-js/pull/623
I'm working on a branch but the error I get is for a local attempt I'm doing in order to see what this plugin produces

**Comment by Swatinem** [comment]
Is this actually working correctly in TS? what kind of `.d.ts` file does typescript generate for the json?

**Comment by HarelM** [comment]
In terms of code this is working as expected, in terms of types generation IDK.
Feel free to take my project and run it locally to see what comes out...
Since writing this I switched to use dts-builder-generator.

**Comment by Swatinem** [comment]
Well in that case I think it doesn’m matter anymore :-D
