### ISSUE TITLE
[Discussion] Typescript 4.5.x and virtual usage.

### ISSUE THREAD

**Issue by typhonrt** [Swatinem/rollup-plugin-dts#187]
Greets @Swatinem; thanks so much for making and maintaining this module! It is tremendously helpful to me and many others I'm sure.

Just wanted to pop in here and mention something I saw when I built [esm-d-ts](https://github.com/typhonjs-node-build-test/esm-d-ts) which automatically creates a bundled TS declaration file from ESM source. Initially I tried to use Typescript `4.5.2` with the latest `rollup-plugin-dts`. Granted this is not supported yet. What I saw though which may be part of your upgrade / maintenance is that when switching between Typescript `4.4.4` and `4.5.2` is that classes were hoisted in the Rollup process. IE some classes instead of exporting the class name would become `<CLASSNAME>$1`. I traced things through the AST manipulation and couldn't see where this occurred, so just something to note when you work on the next version of the plugin supporting `4.5.x`. For my current work it turns out that Typescript `4.4.4` and latest `rollup-plugin-dts` works fine.

Another discussion point I'd like to bounce off you is trying to figure out if there is a way to feed `rollup-plugin-dts` from in memory declarations. Presently with `esm-d-ts` I use the TS compiler to generate intermediary declaration files by default stored under `./.dts` before running Rollup programatically w/ `rollup-plugin-dts`. It would be fantastic to feed the bundling process from in memory resources from the first compilation step. I tried using `@rollup/plugin-virtual` and a virtual file system plugin, but ran into barriers. I'd be glad to help put together a PR to support this, but want to get your input and pointers on any implementation details as your plugin is not trivial.

**Comment by Swatinem** [comment]
The `$1` suffixes are probably because of name collisions. Rollup adds them when you have the same type defined in multiple files. The plugin does not support declaration merging.

And using a virtual loader plugin should be possible. I don’t think the plugin would need any specific changes to make that work, but I could be wrong. It can just consume `.d.ts` files from the file system, but that should equally well if those files are not loaded from the FS.

**Comment by typhonrt** [comment]
> The `$1` suffixes are probably because of name collisions. Rollup adds them when you have the same type defined in multiple files. The plugin does not support declaration merging.

Indeed, but this is a change that happens from simply using Typescript `4.4.4` where there is no hoisting. Switch to `4.5.2` and there is hoisting; same latest Rollup version and DTS plugin, so that was a bit of a puzzle and perhaps something to look out for in your future dev efforts. There are no naming conflicts in the TS declarations used and I traced execution through the AST manipulations and couldn't see any changes, so a bit of a "mystery" that you may encounter soon. 

I'll have to dig a bit deeper on the virtual usage; it doesn't appear like an instant clear cut scenario. It's in the nice to have category as it would allow my build tool / `esm-d-ts` to generate a bundle without intermediary files. I believe `@rollup/plugin-virtual` prepends source IDs with `virtual:<pack / virtual name>` and that didn't play nice w/ your plugin; "somewhere". Ideally figuring out a solution w/ `@rollup/plugin-virtual` would be best since that is an official Rollup plugin vs some of the lesser used virtual file system Rollup plugins. Presently this isn't something I have immediate time to investigate more, but a nice feature to add to your plugin, so definitely wanted to bounce the idea off you for any thoughts / implementation ideas. It seems like some changes might be required in your plugin, but I'm not sure.
