### ISSUE TITLE
Caching issues (at least on Windows)

### ISSUE THREAD

**Issue by vitaly-t** [Swatinem/rollup-plugin-dts#190]
This plugin suffers from some sort of caching issue, at least on Windows.

With every next build, it runs slower and slower.

On my machine with AMD 5900X, 64GB RAM and 7GB/s SSD, it starts with ~700ms, and after a few days goes to 12s to generate declarations.

At this point it doesn't even work right anymore, it keeps generating some obsolete declarations from several versions ago. I've tried to clean up everything, dependencies, all generated files, etc - nothing helped. The only way I was able to make it work again - remove the entire repo, and pull it all over again. Then it starts working again, slowing down after awhile again.

**Environment:**

* NodeJS v16.13.1
* Windows 10
* rollup-plugin-dts v4.1.0

**Comment by Swatinem** [comment]
That is highly unlikely to be caused by this plugin. It does not perform any kind of caching itself. Its more likely either TS or rollup. How are you using it?

**Comment by vitaly-t** [comment]
Nothing special, here's inside my `rollup.config.ts`:

```ts
/**
 * The types.
 */
const dts = {
    ...common,

    output: {
        file: pkg.types,
        format: 'esm',
    },

    plugins: [rollupPluginDts()],
};
```

Unlikely or not, this is exactly what's happening.

**Comment by vitaly-t** [comment]
P.S. This is the complete project - [iter-ops](https://github.com/vitaly-t/iter-ops).

**Comment by Swatinem** [comment]
Looking at your project, you seem to be using `.ts` files directly, which I strongly advise against. Your `tsconfig` has `rootDir: "."`, which I bet is also not very efficient.
If I am not mistaken, your build essentially runs ts typechecking/compilation up to 5 times. So you are leaving a ton of build performance on the table.
I bet most of your slowdown comes from TS being slow, and having it do type checking during your build.

**Comment by vitaly-t** [comment]
That wouldn't explain why the plugin starts producing obsolete declarations that do not correspond to the current code.

**Comment by Swatinem** [comment]
That indeed sounds weird. Does TS do that on its own?

**Comment by vitaly-t** [comment]
Not that I can see.
