### ISSUE TITLE
[bug]generate dts bundle rename type using declare const

### ISSUE THREAD

**Issue by skimhugo** [Swatinem/rollup-plugin-dts#194]
reproduce repo：https://github.com/skimmilk6877/tsup-bugs-1

declare namespace WebGradients {
export {
WebGradients_Key as Key,
};
}

declare const _api$3_Colors: typeof Colors; // wrong line
declare const _api$3_BoxShadow: typeof BoxShadow;
declare const _api$3_WebGradients: typeof WebGradients;
declare namespace _api$3 {
export {
_api$3_Colors as Colors,
_api$3_BoxShadow as BoxShadow,
_api$3_WebGradients as WebGradients,
};
}

**Comment by Swatinem** [comment]
I haven’t looked at the repro. But can you elaborate more on what you are trying to do, and what the xepected outcode should be?

**Comment by skimmilk6877** [comment]
@Swatinem I Guess I have some duplication of name of sub folder, and the rename cause bug.

declare const _api$3_Colors: typeof Colors;

should be 
declare const _api$3_Colors: Colors;
