### ISSUE TITLE
Typos in the repository description

### ISSUE THREAD

**Issue by roj1512** [Swatinem/rollup-plugin-dts#197]
![image](https://user-images.githubusercontent.com/49933115/153883939-f3e3e38a-441f-4dfb-9c21-2e880a1399f6.png)

Please update the repository description to the following:

 A Rollup plugin to generate declarations (.d.ts) files for your TypeScript code.

**Comment by roj1512** [comment]
Why was this closed? I don’t see any changes made to the description.

**Comment by Swatinem** [comment]
I bulk-closed all the issues due to the project moving into maintenance mode: https://github.com/Swatinem/rollup-plugin-dts/issues/277

**Comment by roj1512** [comment]
Oh, it’s alright then. Good luck, and sorry!
