### ISSUE TITLE
[question] does the officail plugin generate d.ts?

### ISSUE THREAD

**Issue by zzzgit** [Swatinem/rollup-plugin-dts#198]
Hi, I am using the official plugin `@rollup/plugin-typescript` and find it super hard to handle to generate `d.ts` files.

I couldn't roll up declaration files and I couldn't get any help from the community.

So, is this plugin aiming to fill in the blanks of the functionality?

**Comment by Swatinem** [comment]
I guess so? Though I’m not really in the position to give support in using `@rollup/plugin-typescript`.
