### ISSUE TITLE
Types for a CommonJS module exporting a single object in module.exports are not generated correctly

### ISSUE THREAD

**Issue by elchininet** [Swatinem/rollup-plugin-dts#204]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Repo

This repository has the necessary code to reproduce this issue as well as an explanation in the README: https://github.com/elchininet/rollup-plugin-dts-issue

### Explanation

In [the README](https://github.com/Swatinem/rollup-plugin-dts/blob/master/README.md) of `rollup-plugin-dts`, the next snippet shows how to use this plugin. The Rollup `output` configuration contains a `format` property:

```javascript
{
    input: "./my-input/index.d.ts",
    output: [{ file: "dist/my-library.d.ts", format: "es" }],
    plugins: [dts()]
}
```

But looking at the code, it does not matter which `format` is specified because [it will be overridden by 'es'](https://github.com/Swatinem/rollup-plugin-dts/blob/6c16e63c14bcd0447eaf9955f17d0534114e1f31/src/transform/index.ts#L66). The same happens with `exports` that will always be `named`.

But check the repo provided. I‘m creating a `CommonJs` module with `format` `cjs` and `exports` `default` form a code written with ES modules. After the `Rollup` bundling process, the module is exported as:

```javascript
function square(n) {
    return n * n;
}

module.exports = square;
```

So, the definition should be:

```javascript
declare function square(n: number): number;

export = square;
```

Instead of:

```javascript
declare function square(n: number): number;

export { square as default };
```

Which corresponds to the declarations of the original ES module, not the declaration of the `Rollup` bundle.

**Comment by Swatinem** [comment]
ES module format is the only thing that is supported.

**Comment by elchininet** [comment]
Thanks for your fast response, @Swatinem.
It would be good to state it clearly in the README as well as remove the `format: "es"` from the snippet because it gives the idea that it can be changed.
Regards.
