### ISSUE TITLE
Broken with rollup@2.75.0+

### ISSUE THREAD

**Issue by Mister-Hope** [Swatinem/rollup-plugin-dts#208]
Results of rollup@2.74.1

```ts
interface DateDetail {
    year?: number | undefined;
    month?: number | undefined;
    day?: number | undefined;
    hour?: number | undefined;
    minute?: number | undefined;
    second?: number | undefined;
}
interface DateInfo {
    display: string;
    value: Date | undefined;
    detail: DateDetail;
}
declare const getDate: (date: string | Date | undefined, options?: DateOptions) => DateInfo | null;
```

Result with 2.75.0 and 2.75.1

```ts
interface DateInfo {
    display: string;
    value: Date | undefined;
    detail: DateDetail;
}
declare const getDate: (date: string | Date | undefined, options?: DateOptions) => DateInfo | null;
```

I do not think any reproduction is needed, you can just write some code with 

- type A (referenced by type B)
- type B (used by code actually)

Any type A is lost here

Any idea? Shall it be rollup issue or the plugin needs to rewrite some lines to compatable with 2.75.0+

**Comment by Swatinem** [comment]
Looks like fallout from https://github.com/rollup/rollup/pull/4510.
Lots of internal testcases are failing, so there is enough to reproduce this.

**Comment by Swatinem** [comment]
I filed https://github.com/rollup/rollup/issues/4514 upstream since this looks like it is broken there.
Also https://github.com/Swatinem/rollup-plugin-dts/pull/211 will construct a bit more code to convince rollup to retain referenced items.

**Comment by Swatinem** [comment]
This was fixed upstream, and should work again with `rollup@2.75.3`.
