### ISSUE TITLE
Namespace remapping inconsistence with dependent type

### ISSUE THREAD

**Issue by lmartorella** [Swatinem/rollup-plugin-dts#213]
### Checklist

* [ X ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ X ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ X ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

Remapping the types during the bundle operation can likely cause dependent types to be wrongly referred outside the mapping. This seems to be a logical issue rather than an implementation issue, and I think that this can be fixed only running a deep AST analysis of the source files (and so likely a task for Typescript itself, rather than an external tool).

### Code Snipped

A simple declaration file like this:

```ts
// file1.d.ts
export declare class Class1 {
}
export declare const f: () => Class1;
```

will indirectly exposes `Class1` via function call return value (but the same can happen via class members, generic default types, etc..).

Remapping the above in a namespace file with

```ts
// index.d.ts
export * as ns from "./file1";
```

will correctly generate a bundled code like this one:

```ts
// This is "bundled.d.ts" 

declare class Class1 {
}
declare const f: () => Class1;

type file1_d_Class1 = Class1;
declare const file1_d_Class1: typeof Class1;
declare const file1_d_f: typeof f;
declare namespace file1_d {
  export {
    file1_d_Class1 as Class1,
    file1_d_f as f,
  };
}

export { file1_d as ns };
```

### The issue

Trying to consume the above declaration file from an application like this:

```ts
// This is app.ts

import { ns } from "./bundled";
export const x = ns.f();
```

(without explicitly typing the `x` variable) will cause this Typescript error:

```text
app.ts:3:14 - error TS4023: Exported variable 'x' has or is using name 'Class1' from external module "./bundled" but cannot be named.

3 export const x = ns.f();
```

even if the `Class1` type was correctly re-exported in the new namespace.

Without bundling the `.d.ts` files, the Typescript compiler will understand from the `export * as ns from "./file1"` statement that everything inside that should be remapped and re-exposed inside such namespace. This applies then to the `Class1` return type as well:

```ts
// Result of the build using the unbundled `index` rather than `bundled`
// app.d.ts
import { ns } from "./index";
export declare const x: ns.Class1;
```

I think the issue is due to the fact that the types are referred inside the bundled namespace, rather than being completely "re-defined" in it.

I've tried to fiddle with the bundled module, and tried to export the Class1 directly:

```ts
// modified bundled.d.ts file
export declare class Class1 {    // Added `export`
}
declare const f: () => Class1;

type file1_d_Class1 = Class1;
declare const file1_d_Class1: typeof Class1;
declare const file1_d_f: typeof f;
declare namespace file1_d {
  export {
    file1_d_Class1 as Class1,
    file1_d_f as f,
  };
}

export { file1_d as ns };
```

but in this case the compiled output of the app compilation will become:

```ts
export declare const x: import("./bundled").Class1;
```

that is wrong, since the `bundled` module exposes `Class1` via namespace object `ns` only.

(Interestingly enough, the Typescript compiler - without bundling - even accepts the `Class1` to not be exported at all in the original `file1` source. It seems that exporting the `f` function causes to all the dependent types to be considered "exported" as well, and visible from the `ns` namespace.)

Thanks, 
 L

**Comment by Swatinem** [comment]
Thanks for the detailed analysis!

I wish it would be possible to simply export things directly from namespaces, which would make this whole re-declaration unnecessary.

Alas, TS does not allow that. Which leads to the problem you are seeing as the return type really is a different declaration than whatever is being exported from the namespace :-(
