### ISSUE TITLE
Question / Error: Could not resolve entry module (./types/index.d.ts)

### ISSUE THREAD

**Issue by rpearce** [Swatinem/rollup-plugin-dts#214]
### Notes

Hi and thank you for making this! I'm trying to have `@rollup/plugin-typescript` build my little react component into a single module, generate the declaration files, and have `dts` save the day for the declarations.

I've tried following a number of other projects' usage, but I keep running into this issue where `dts` can't find the outputted declaration from the prior step.

Am I doing something incredibly wrong, or is this supposed to be working but isn't?

Thanks for your help!

### Checklist

* [ ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
import ts from '@rollup/plugin-typescript'
import dts from 'rollup-plugin-dts'

export default [
  {
    input: './source/index.ts',
    output: { file: './dist/index.js', format: 'es' },
    external: ['react', 'react-dom'],
    plugins: [ts()],
  },
  {
    input: './types/index.d.ts',
    output: { file: './dist/index.d.ts', format: 'es' },
    plugins: [dts()],
  },
]
```

```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": true,
    "declarationDir": "./types",
    "emitDeclarationOnly": true,
    "esModuleInterop": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist",
    "removeComments": true,
    "sourceMap": false,
    "strict": true,
    "target": "es2020"
  },
  "include": ["./source/index.ts"]
}
```

### Error Message

```
λ rm -rf dist && rm -rf types && ./node_modules/.bin/rollup -c rollup.config.js

./source/index.ts → ./dist/index.js...
created ./dist/index.js in 969ms

./types/index.d.ts → ./dist/index.d.ts...
[!] Error: Could not resolve entry module (./types/index.d.ts).
Error: Could not resolve entry module (./types/index.d.ts).
    at error (/Users/bobert/projects/react-medium-image-zoom/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/Users/bobert/projects/react-medium-image-zoom/node_modules/rollup/dist/shared/rollup.js:22527:20)
    at async Promise.all (index 0)
```

**Comment by Swatinem** [comment]
I can only point to https://github.com/rollup/plugins/tree/master/packages/typescript#declaration-output-with-outputfile and to double-check these things work correctly. I think rollup should execute each of these steps in sequence. So if the previous plugin writes these files, then the plugin should find those.

**Comment by rpearce** [comment]
Thanks for the quick reply, @Swatinem. I'll keep digging over the next few nights, and I'll see if I can get a tiny demo repo for you.

**Comment by rpearce** [comment]
Ok, I figured it out with that link you shared! I needed to pass the `tsconfig` option to `ts()`, and I needed to specify a _relative_ place to put type declarations. Since rollup does its own thing, I decided to override the `declarationDir` in the rollup config.

```js
import ts from '@rollup/plugin-typescript'
import dts from 'rollup-plugin-dts'

export default [
  {
    input: './source/index.ts',
    output: { file: './dist/index.js', format: 'es' },
    external: ['react', 'react-dom'],
    plugins: [ts({
      tsconfig: './tsconfig.json',
      compilerOptions: { declarationDir: './types' },
    })],
  },
  {
    input: './dist/types/index.d.ts',
    output: { file: './dist/index.d.ts', format: 'es' },
    plugins: [dts()],
  },
]
```

And then removing `declarationDir` from the regular `tsconfig.json` to let it do its own thing if ran normally with `tsc`:

```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": true,
    "emitDeclarationOnly": true,
    "esModuleInterop": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist",
    "removeComments": true,
    "sourceMap": false,
    "strict": true,
    "target": "es2020"
  },
  "include": ["./source/index.ts"]
}
```

This generates `./dist/types/` at the end of the day, so as part of my build process I just `rm -rf ./dist/types`.

As a last question, do you typically commit those built types and keep those around? Thanks for your help earlier!
