### ISSUE TITLE
Unexpected output when using `output.dir` and `preserveModules: true`

### ISSUE THREAD

**Issue by WesSouza** [Swatinem/rollup-plugin-dts#215]
A project I'm working on uses `output.dir` in combination with `preserveModules: true` to generate individual files that can be consumed by an import statement, such as:

```ts
import myTheme from "my-library/dist/themes/my-theme"
```

This is an additional export and this plugin seems to not handle it well.

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
* [x] This issue is not related to rolling up `@types`.

### Code Sample

https://github.com/WesSouza/rollup-plugin-dts-dir-bug/

### Expected `dist` Output

```
dist
|- [ ] themes
|   |- index.d.ts
|   |- index.js
|   |- one.js
|   |- one.d.ts
|   |- two.js
|   '- two.d.ts
|- index.d.ts
|- index.js
'- index.mjs
```

### Actual `dist` Output

```
dist
|- [ ] themes
|   |- [ ] common          <--- Structure from `src`
|   |   |- [ ] themes
|   |       '- index.d.ts  <--- Imports ../../types.js
|   |- index.js
|   |- one.js
|   |- two.js
|   '- types.d.ts
|- index.d.ts
|- index.js
'- index.mjs
```

Albeit there is a discrepancy between exporting a subfolder that depends on a type file external to it, I'd expect at least the plugin to generate `.d.ts` files for each of the exported JS files.

**Comment by Swatinem** [comment]
I’m wondering why you need rollup at all for this use case? Wouldn’t `tsc` emit output be exactly what you would expect?

**Comment by WesSouza** [comment]
The output structure is different and rollup is also used of esbuild to transpile the code.
