### ISSUE TITLE
keyof returns unexpected results

### ISSUE THREAD

**Issue by Stevemoretz** [Swatinem/rollup-plugin-dts#216]
### Checklist

* [ X ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ X ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ X ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
type TESTING_TYPES = {
    childrenStyle: {
        "*"?: ViewProps["style"];
        line?: ViewProps["style"];
        media?: ViewProps["style"];
        [key: string]: ViewProps["style"];
    };
};

type TESTING_TYPES2 = {
    childrenStyle: {
        "*"?: ViewProps["style"];
        line?: ViewProps["style"];
        media?: ViewProps["style"];
    };
};

export type Props = { 
    inheritStyles4: keyof TESTING_TYPES["childrenStyle"];
    inheritStyles5: keyof TESTING_TYPES2["childrenStyle"];

}
```

### Error Message

```
// No error message
```

the output is : 

```ts
type RESULT = {
    inheritStyles4: string | number;
    inheritStyles5: "line" | "*" | "media";
}
```

inheritStyles4 is ruined and I get no autocompletion anymore. the result should be : `"line" | "*" | "media" | string` instead of `string | number`

By the way a great plugin, I love it!

**Comment by Swatinem** [comment]
This is interesting.

The plugin by itself does not do inlining of type information. Especially not one that relies on the type information from the typescript type checker, like inlining `keyof`.

This seems to be coming from typescript directly and is explained here: https://www.typescriptlang.org/docs/handbook/2/keyof-types.html

> Note that in this example, M is string | number — this is because JavaScript object keys are always coerced to a string, so obj[0] is always the same as obj["0"].

**Comment by Stevemoretz** [comment]
> This is interesting.
> 
> The plugin by itself does not do inlining of type information. Especially not one that relies on the type information from the typescript type checker, like inlining `keyof`.
> 
> This seems to be coming from typescript directly and is explained here: https://www.typescriptlang.org/docs/handbook/2/keyof-types.html
> 
> > Note that in this example, M is string | number — this is because JavaScript object keys are always coerced to a string, so obj[0] is always the same as obj["0"].

That was quick!!!!
Wow thank you so much I had no idea this wasn't related to your plugin! I'm sorry.

So I used this : https://stackoverflow.com/a/66252656/10268067

and got it working! Thank you so much again.
