### ISSUE TITLE
Incorrect generated types: TS2344 error for type parameter extending string

### ISSUE THREAD

**Issue by vezwork** [Swatinem/rollup-plugin-dts#217]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

Type generated by TypeScript:
```ts
export interface Example<S extends string> {
// ...
```

Output in `index.d.ts` generated by `rollup-plugin-dts`:
```ts
type index_d_Example<_0> = Example<_0>;
```
Which causes TypeScript error `TS2344: Type '_0' does not satisfy the constraint 'string'.` 

### Error Message

No error message is thrown by rollup or the plugin, the issue is rather that the outputted types are incorrect.

Expected output that fixes this issue:
```ts
type index_d_Example<_0 extends string> = Example<_0>;
```

**Comment by vezwork** [comment]
Reproduced in CodeSandbox: https://codesandbox.io/s/rollup-plugin-dts-issues-217-repro-cs7ibq?file=/dist/example.d-2be15cad.d.ts

**Comment by tch0m** [comment]
This issue is affecting us too

**Comment by Swatinem** [comment]
Which version of the plugin are you using?
This looks very much like https://github.com/Swatinem/rollup-plugin-dts/issues/185 which was already fixed long ago.

Reproducing this with the example you gave gives me:
```
interface Example<S extends string> {
  example: S;
}
declare const dog: Example<"hi">;
type example_d_Example<S extends string> = Example<S>;
declare const example_d_dog: typeof dog;
declare namespace example_d {
  export {
    example_d_Example as Example,
    example_d_dog as dog,
  };
}
export { example_d as types };
```
