### ISSUE TITLE
Fully comply with LGPLv3

### ISSUE THREAD

**Issue by amznpurple** [Swatinem/rollup-plugin-dts#221]
Hiya,

Long story short, could you include a full copy of the LGPL and GPL in this project so that we can fully comply with the LGPLv3?

If you'd like me to guide you on the patch for this, please let me know, I am happy to do so.

Much appreciated, thanks.

---

As per the LGPLv3 from: https://www.gnu.org/licenses/lgpl-3.0-standalone.html

> a) Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License.
> b) Accompany the object code with a copy of the GNU GPL and this license document.

**Comment by Swatinem** [comment]
Ah that would be good.
I recently added the LGPL to another one of my projects: https://github.com/Swatinem/rust-cache/blob/master/LICENSE

I was not aware that you also need the whole GPL text as well. I would appreciate an example of how that would look like.

**Comment by amznpurple** [comment]
>  I recently added the LGPL to another one of my projects: https://github.com/Swatinem/rust-cache/blob/master/LICENSE

Nice!

> I was not aware that you also need the whole GPL text as well.

It is not especially common, but not rare either that everyone does this.

> I would appreciate an example of how that would look like.

Of course! Many people add two files.

First add:
COPYING (containing the GPLv3)

Also add (for LGPLv3+):
COPYING.LESSER (containing the LGPLv3)

Instead some people name it:
COPYING.LGPL3

Longer instructions are available here:
https://www.gnu.org/licenses/gpl-howto.html

I'm not a lawyer, but I work in this space. Feel free to ping if you have any other questions or would like me to review a PR.

Cheers!

cc @purpleidea

**Comment by Swatinem** [comment]
To be completely honest, this is a bit concerning to me.

While I do want my project to have a strong copyleft license, I also appreciate the the reservations people might have against the "infectious" nature of the GPL.

I want people to be able to use the plugin freely as a (non-bundled) dependency without concerns.

Advertising the "infectious" GPL as the "primary" license does send the wrong message though, doesn’t it?
Also not sure what automatic license scanning software would do in that case?

**Comment by amznpurple** [comment]
You have to make your own decisions here, but what the GPL family of licenses does is prevent someone from taking your code and putting it into something proprietary (while sometimes also modifying it) without necessarily giving that code back. License choice is a complex topic and I can't be your guide, but think about things and good luck with whatever choice you make. I don't think "infectious" is a good way to describe the GPL. I also thought you were intending to use this as LGPL.
Cheers

**Comment by amznpurple** [comment]
Just to clarify: To use the LGPL, you include the text of the GPL, but it's the LGPL that applies, not the GPL.

**Comment by Swatinem** [comment]
Thanks for reminding and bearing with me on this.
Indeed the LGPL is just an amendment to the GPL so the GPL text also needs to be there ;-)
