### ISSUE TITLE
rollup-plugin-dts blocks first entry output in rollup watch mode, when used in 2nd entry

### ISSUE THREAD

**Issue by taran-d** [Swatinem/rollup-plugin-dts#222]
### Checklist

* [-] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [+] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [+] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

tsconfig.json:
```
{
  "compilerOptions": {
      "target": "es5",
      "module": "esnext",
      "rootDir": ".",
      "outDir": "dist",
      "declaration": true,
  },
}

```

package.json:
```
{
  "name": "Rollup-dts-bug",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "MIT",
  "scripts": {
    "start": "rimraf dist & rollup -c -w"
  },
  "devDependencies": {
    "rollup": "^2.79.0",
    "tslib": "^2.4.0",
    "typescript": "^4.8.3",
    "@rollup/plugin-typescript": "^8.5.0",
    "rimraf": "^3.0.2",
    "rollup-plugin-dts": "^4.2.2"
  }
}
```

Rollup config:
```ts
[
  {
    input: 'src/index.ts',
    output: [
      {
        file: 'dist/index.js',
        format: 'es',
      },
    ],
    plugins: [
      typescript(),
    ],
  },
  {
    input: 'dist/src/index.d.ts',
    output: [{ file: 'dist/index.d.ts', format: 'es' }],
    plugins: [dts()],
  }
]
```

index.ts :
```
export function test(a: number, b: number) {
  console.log("Counting sum");
  console.log(a, b);
  return a + b;
}
```

### Error

Whenever i add something in index.ts file, generated index.js file has no changes. For example, add this line `console.log("Counting sum 2");` anywhere in the test function and save the file. dist/index.js  remains the same and it looks like dts plugin is blocking rebuild.

**Comment by Swatinem** [comment]
I don’t really test this plugin with watch mode. but on the other hand, it also shouldn’t interfere with it in any way. Especially two rollup plugins chained together should not have an effect on each other.

**Comment by Seigiard** [comment]
Faced same problem. 

Separately typescript and dts plugins work well, but in one config — same behavior as described.

Solve this problem by concurrent run two rollup configs: one for TS, another for DTS. But this is very inconvenient.
