### ISSUE TITLE
`namespace` exports circularly references themselves

### ISSUE THREAD

**Issue by kraenhansen** [Swatinem/rollup-plugin-dts#223]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

I've pushed a reproduction of this https://github.com/kraenhansen/rollup-plugin-dts-issue-223

```ts
// thing.ts
export class Thing {};
```

```ts
// index.ts
import * as thing from "./thing";
export namespace MyNamespace {
  export type Thing = thing.Thing;
}
```

Results in the following output:

```ts
// types.d.ts
declare class Thing {
}

declare namespace MyNamespace {
    type Thing = Thing;
}

export { MyNamespace };
```

### Error Message

The `type Thing = Thing;` in the output file above yields:

```
Type alias 'Thing' circularly references itself.
```

Which effectively results in the type being `any` for a consumer (see `consumer.ts` in the reproduction).

### Workaround

Note that if I add a local type alias in the `index.ts`, the output turns out as expected:

```ts
// index.ts
import * as thing from "./thing";
type MyThing = thing.Thing;
export namespace MyNamespace {
  export type Thing = MyThing;
}
```

yields

```ts
// types.d.ts
declare class Thing {
}

declare type MyThing = Thing;
declare namespace MyNamespace {
    type Thing = MyThing;
}

export { MyNamespace };

```

**Comment by Swatinem** [comment]
Thanks for the report!
This is unfortunately a restriction that TS does variable hoisting for namespaces. Working around this is annoying and fragile :-(

**Comment by kraenhansen** [comment]
@Swatinem how / when was this fixed?

**Comment by Swatinem** [comment]
I mass-closed all the issues, as I transition the project into maintenance mode and won’t be working on any of it, see https://github.com/Swatinem/rollup-plugin-dts/issues/277
However I wasn’t able to mass-close-and-comment mentioning that.
