### ISSUE TITLE
Add support for .mts and .cts files

### ISSUE THREAD

**Issue by RebeccaStevens** [Swatinem/rollup-plugin-dts#228]
Currently any files with the extensions `.mts` or `.cts` are ignore by this plugin. They should be handled the same as `.ts` files.

### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

**Comment by Gotos** [comment]
Stumbled over this issue today as well; are there any good workarounds until this plugin supports mts and cts files?
