### ISSUE TITLE
rollup-plugin-dts output does not include type imports from 'react'

### ISSUE THREAD

**Issue by JeremyRippert** [Swatinem/rollup-plugin-dts#236]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

Rollup config

```js
import dts from "rollup-plugin-dts";

export default {
  input: "types/index.d.ts",
  output: [{ file: "types/rolled.d.ts", format: "esm" }],
  plugins: [dts()],
};
```

`types/index.d.ts`

```ts
import React, { MouseEventHandler } from "react";
declare type Props = {
    onClick: MouseEventHandler<HTMLButtonElement>;
};
export declare const Button: React.FC<Props>;
export {};
```

### Error Message

The output is missing `MouseEventHandler`, resulting in `type MouseEventHandler = /*unresolved*/ any`

Output:

```ts
import React from 'react'; // <- missing { MouseEventHandler }

declare type Props = {
    onClick: MouseEventHandler<HTMLButtonElement>;
};
declare const Button: React.FC<Props>;

export { Button };
```

**Edit** For now, I have replaced `onClick: MouseEventHandler<HTMLButtonElement>;` by `onClick: React.MouseEventHandler<HTMLButtonElement>;`

Which results in a working output:

```ts
import React from 'react';

declare type Props = {
    onClick: React.MouseEventHandler<HTMLButtonElement>;
};
declare const Button: React.FC<Props>;

export { Button };
```

**Comment by danielbarion** [comment]
```
import dts from 'rollup-plugin-dts'

export default {
  input: './src/index.tsx',
  output: [{ file: 'dist/react-tooltip.d.ts', format: 'es' }],
  plugins: [
    dts({
      compilerOptions: {
        baseUrl: 'src',
        importHelpers: true,
      },
    }),
  ],
}

```

This is working for me, the types from dependencies are exported as expected

**Comment by JeremyRippert** [comment]
Thanks for your answer. I've copy / pasted your config and tried with my `index.tsx`, output is still incorrect on my end

`rollup.config.js`

```
import dts from "rollup-plugin-dts";

export default {
  input: "./src/index.tsx",
  output: [{ file: "dist/react-tooltip.d.ts", format: "es" }],
  plugins: [
    dts({
      compilerOptions: {
        baseUrl: "src",
        importHelpers: true,
      },
    }),
  ],
};
```

`src/index.tsx`
```
import React, { MouseEventHandler } from "react";

type Props = {
  onClick: MouseEventHandler<HTMLButtonElement>;
};

export const Button: React.FC<Props> = ({ onClick }) => {
  return <button onClick={onClick}>Click me</button>;
};
```

`dist/react-tooltip.d.ts`

```
import React from 'react';

declare type Props = {
    onClick: MouseEventHandler<HTMLButtonElement>;
};
declare const Button: React.FC<Props>;

export { Button };
```

I am using `"rollup-plugin-dts": "4.2.2",`

**Comment by danielbarion** [comment]
Hi!
I'm using `"rollup-plugin-dts": "^5.0.0",`

Please take a look at: https://github.com/ReactTooltip/react-tooltip/blob/master/rollup.config.types.js

I hope this helps you.

You can clone the repository and run `yarn build` and check the generated types in `dist` folder

**Comment by Swatinem** [comment]
https://github.com/Swatinem/rollup-plugin-dts/tree/master/tests/testcases/issue-236 This works just fine.
Must be an issue related to compiling the `.tsx` file. You can work around that by bundling pre-compiled `.d.ts` files.
