### ISSUE TITLE
Plugin does not support `Omit` with types declared in .tsx files

### ISSUE THREAD

**Issue by Crisnzx** [Swatinem/rollup-plugin-dts#242]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
type AutocompleteProps = Omit<InputProps, "type"> & {
  options: Option[];
};

export const Autocomplete = ({}: AutocompleteProps) => {
  return <div></div>;
};
```

### Error Message

```
(plugin dts) Error: Syntax not yet supported
  73 |           type={type}
  74 |           value={mask ? undefined : value}
> 75 |           onChange={(event) => !mask && onChange?.(event.target.value)}
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  76 |           readOnly={isInitiallyReadOnly || readOnly}
  77 |           onFocus={handleFocus}
  78 |           placeholder={placeholder}
src/components/form-components/inputs/input/index.tsx
```

When I try to use Omit using an existing type of my project the plugin starts to throw errors related to syntax not supported, pointing out the JSX syntax of the component where the type was exported, in my case, the `Input` component, where `InputProps` is defined and exported.

I know the `Input` component doesn't have issues because when I try to compile the project removing the `Omit` everything works fine. And I also tested using the `Omit` with other component types of my project and the same error occurred.

It's important to mention that using Omit with an external type, like the React types, and using a type defined in a `.ts` file, it works properly. But when the type is defined in the project in a `.tsx` file we have this error, getting an error message that blames the wrong thing.

**Comment by Swatinem** [comment]
I believe the usage of `Omit` might be misleading here.
The problem is that it tries to use the `.tsx` file, and not a pre-compiled `.d.ts` files. So it is rather that it tries to parse the full `tsx` file, and not only the type definitions. Its not entirely clear why though.

**Comment by Crisnzx** [comment]
Got it... My workaround was to move the type definition to a new `.ts` file and then it worked as expected
