### ISSUE TITLE
Nested namespace identifiers errors with `namespace must have a "ModuleBlock" body`

### ISSUE THREAD

**Issue by kraenhansen** [Swatinem/rollup-plugin-dts#246]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
declare namespace Foo.Bar {}
```

### Error Message

```
Error: namespace must have a "ModuleBlock" body.
```

### Details

I get this error when using the shorthand for nesting namespaces (separating identifiers with dots).

I believe this is a more general case of https://github.com/Swatinem/rollup-plugin-dts/issues/160.

Looking at [the AST for this](https://ts-ast-viewer.com/#code/CYUwxgNghgTiAEA7KBbEBnADlMCBiA9gQHQBCs8A3gL4BQQA), the `body` of the first `ModuleDeclaration` is indeed another `ModuleDeclaration` and not a `ModuleBlock` as [expected by the plugin](https://github.com/Swatinem/rollup-plugin-dts/blob/v5.1.1/src/transform/DeclarationScope.ts#L336).

Patching the [default value of `relaxedModuleBlock `](https://github.com/Swatinem/rollup-plugin-dts/blob/v5.1.1/src/transform/DeclarationScope.ts#L328) to `true` seems to solve the problem, but what would the drawback of that be?

**Comment by kraenhansen** [comment]
This too. How was it "completed", when was / is the fix released?

**Comment by Swatinem** [comment]
I mass-closed all the issues, as I transition the project into maintenance mode and won’t be working on any of it, see https://github.com/Swatinem/rollup-plugin-dts/issues/277
However I wasn’t able to mass-close-and-comment mentioning that.

**Comment by kraenhansen** [comment]
Sure - I get the feeling of not having the time to drive actively drive project.
I do however find it a bit misleading that you're close issues, especially as "completed"?
Why not keep them around for others to find and contribute fixes for, as you're stating you welcome
