### ISSUE TITLE
Missing `declare` in un-exported top-level elements

### ISSUE THREAD

**Issue by hyrious** [Swatinem/rollup-plugin-dts#254]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
// foo.d.ts
export enum Color { Red, Green, Blue }
export interface Foo { bar: Color }

// main.d.ts
export { Foo } from './foo'
```

### Error Message

When you bundle main.d.ts using rollup-plugin-dts, it generates an invalid file:

```ts
// out.d.ts
enum Color { Red, Green, Blue }  // ts(1046): ...
interface Foo { bar: Color }
export { Foo }
```

ts(1046) means you have to add `declare` or `export` to all entities (not types) from declarations, for example `const`, `enum`, `class`, `namespace`. They both have real JS objects.

The reason behind, I can think of, is that Rollup collects `export` names and put the export statement at the end of the file. This is correct for JS modules.

```js
// input
export const Color = {}

// rollup
const Color = {}
export { Color }
```

...But not correct for some elements in TS.

I found this issue from a weird workaround in [tsup](https://github.com/egoist/tsup/issues/834), which uses rollup-plugin-dts to bundle a type from terser. Usually you won't run into this issue because typings generated by `tsc` would have `declare enum` statements. But the typings in terser is written by hand and they don't write `declare`. 😐

In addition, here's a notable case you may need to take care of:

```ts
declare namespace Foo {
  declare enum Color {}  // ts(1038): cannot use `declare` in namespace
}
```

**Comment by hyrious** [comment]
> types can contain hand-crafted code which is known to cause issues.

This issue can be arranged here too..

**Comment by hyrious** [comment]
Ok I found the code that fixes modifiers..

https://github.com/Swatinem/rollup-plugin-dts/blob/8dda1a0ed3d950ba93ced7e871d07c6b337846c9/src/transform/preprocess.ts#L319

Need I create a PR to add `ts.isEnumDeclaration(node) ||` ?

**Comment by Swatinem** [comment]
Yes, I believe that should do the trick. PR welcome
