### ISSUE TITLE
(plugin dts) Error: Syntax not yet supported

### ISSUE THREAD

**Issue by richbachman** [Swatinem/rollup-plugin-dts#257]
### Checklist

* [ ] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [ ] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

I'm running into a build error in a monorepo using turborepo and rollup to build the types. The error isn't very helpful so I'm not able to track down what part of the code is causing the issue.

Here is a link to the repo: https://github.com/richbachman/dsys-test

To reproduce, run `pnpm install` and then `pnpm build`. Do you have any suggestions on how to better track down the cause of the error? Thanks!

### Code Snipped

https://github.com/richbachman/dsys-test/blob/main/packages/ui/rollup.config.mjs#L80

```ts
dts({
        compilerOptions: {
          ...compilerOptions,
          baseUrl: path.resolve(compilerOptions.baseUrl || "."),
          declaration: true,
          noEmit: false,
          emitDeclarationOnly: true,
          noEmitOnError: true,
          target: baseTs.ScriptTarget.ESNext,
        },
      }),
```

### Error Message

```
@design-system/ui:build: src/index.ts → dist...
@design-system/ui:build: [!] (plugin dts) Error: Syntax not yet supported
@design-system/ui:build:
@design-system/ui:build: > 1 | {"version":3,"file":"index.d.ts","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":"AAAA,cAAc,mBAAmB,CAAC;AAClC,cAAc,kBAAkB,CAAC;AACjC,cAAc,oBAAoB,CAAC"}
@design-system/ui:build:     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@design-system/ui:build: src/index.ts
@design-system/ui:build:     at Transformer.convertStatement (file:///Users/richard.bachman/Fivetran/design-system/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1297:19)
```

**Comment by Swatinem** [comment]
Well, looks like some sourcemap was fed to the plugin.

**Comment by richbachman** [comment]
I found the bug in my code.

**Comment by brandonpittman** [comment]
@richbachman Can you tell me the bug?
