### ISSUE TITLE
The output directory structure in multi-entry mode is not expected

### ISSUE THREAD

**Issue by ambar** [Swatinem/rollup-plugin-dts#262]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [ ] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

https://github.com/ambar/rollup-dts-demo

```ts
{
  input: ['src/client.ts', 'src/server.ts'],
  output: {
    format: 'esm',
    dir: 'types',
  },
  plugins: [dts()],
}
```

### Error Message

```sh
npm run build && tree types

✨  Done in 0.77s.

types
├── shared-e3276c26.d.ts
└── src  # 👈🏼 unexpected, do not want to have it
    ├── client.d.ts
    └── server.d.ts
```

**Comment by igordanchenko** [comment]
@ambar, I believe you can specify the desired chunk names by providing the `input` prop as an object as follows:

```js
export default {
  input: {foo: 'src/foo.ts', bar: 'src/bar.ts'},
  output: {format: 'esm', dir: 'types'},
  plugins: [dts()],
}
```

**Comment by ambar** [comment]
@igordanchenko Nice workaround, thank you! I've updated the description a bit and now I think it's just a nice-to-have feature.
