### ISSUE TITLE
Declaration source maps are broken

### ISSUE THREAD

**Issue by mrazauskas** [Swatinem/rollup-plugin-dts#280]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
export function sum(a: string, b: string) {
  return a + b;
}
```

### Repro

To make life easier, I have created reproduction repo: https://github.com/mrazauskas/x-rollup-declaration-map

Please clone it and follow these steps to reproduce the issue:

1. Run `yarn` to install dependencies.
2. Run `yarn build --declarationMap`. It will use `tsc` directly, the resulting declaration file and its source map can be found in the `./build` directory.
3. Run `yarn bundle --sourcemap`. It will use Rollup together with the `rollup-plugin-dts`, the resulting declaration file and its source map can be found in the `./bundle` directory. `sourceMappingURL` is included in the `index.d.ts` file, but unfortunately the `index.d.ts.map` is broken.

I would expect to have working `index.d.ts.map` in the `./bundle` directory. Why not? Rollup has great support for source maps.

**Comment by Swatinem** [comment]
Declaration SourceMaps are generally not supported. Feature development has also halted on this project, see #277

**Comment by mrazauskas** [comment]
Thanks. This is your project. Just wanted to draw attention.

**Comment by llllvvuu** [comment]
@mrazauskas could you share the repo again? I am considering to make a fork with this feature

**Comment by mrazauskas** [comment]
I don't have it any more, but it was rather simple project with two `ts`. Building it with `tsc` was emitting the mapping for `.d.ts`. But building it with Rollup with `--sourcemap` flag was emitting empty/broken mapping.
