### ISSUE TITLE
Modify engines.node>=16

### ISSUE THREAD

**Issue by curlykay9527** [Swatinem/rollup-plugin-dts#282]
When using the "engine-strict = true" configuration in .npmrc, it is easy to encounter installation failures for version 6.0.0 if the latest LTS version of Node is not used.
Due to the project entering a maintenance state, unless there is a specific requirement to use Node version 18.7.1, it is recommended to set the minimum required Node version to >=16.

**Comment by Swatinem** [comment]
I’m happy to take a PR that lowers the requirements to >=16.

**Comment by curlykay9527** [comment]
`renovate[bot]` will regularly modify engines.node to the latest version 3cead14ada32de3af636b604efdf4dcf486a2072, which makes the pr #283  invalid.
hope to modify the dependency update strategy of `renovate [bot]` to ignore updates for engines.node.

**Comment by Swatinem** [comment]
Either one of those should be fine really.
I will close this issue for now, as https://github.com/Swatinem/rollup-plugin-dts/blob/master/CHANGELOG.md#601 was released with a version set to 16. Happy to take further PRs to avoid renovate messing with this, it has been annoying me as well.
