### ISSUE TITLE
Namespaced type is exported as "export type" instead of just "export"

### ISSUE THREAD

**Issue by hazae41** [Swatinem/rollup-plugin-dts#284]
### Checklist

* [x] I can reproduce this issue when running this plugin on its own.
  *Other plugins, such as `node-resolve` are known to cause issues.*
* [x] I am running this plugin on `.d.ts` files generated by TypeScript.
  *The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues.*
* [x] This issue is not related to rolling up `@types`.
  *The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues.*

### Code Snipped

```ts
export interface MyInterface {
  // stuff
}

export namespace MyInterface {
  // stuff
}
```

### Produced Result

In 6.0.0 the output is this

```tsx
interface MyInterface {
  // stuff
}
declare namespace MyInterface {
  // stuff
}

export type { MyInterface };
```

When used in other projects, this error is thrown:

`'MyInterface' cannot be used as a value because it was exported using 'export type'.`

### Expected Result

In 5.3.0 the result is this

```tsx
interface MyInterface {
  // stuff
}
declare namespace MyInterface {
  // stuff
}

export { MyInterface };
```

**Comment by hazae41** [comment]
The bug was added in https://github.com/Swatinem/rollup-plugin-dts/commit/1b228d052785ea7ad061967430d3ed560582c46c

**Comment by hazae41** [comment]
@mithodin

**Comment by mithodin** [comment]
Interesting, I thought I had accounted for that kind of situation. Shouldn't be too hard to fix though.
