### ISSUE TITLE
Consider changing project direction

### ISSUE THREAD

**Issue by Swatinem** [Swatinem/rollup-plugin-dts#29]
I have been thinking a lot lately about TS project management in general and even started a small [blog](https://swatinem.de/blog/dx-small-projects/) [series](https://swatinem.de/blog/managing-intermediates/) on this topic. This, combined with some issues and requests for this projects made me rethink the project direction.

I would appreciate some feedback on these ideas.
CC @aleclarson @robhicks @timocov @octogonz

# How it works now

The plugin currently uses the typescript `createProgram` and `emit` APIs to basically typecheck your whole code ahead of time, and emit `declaration` files for each source file.

This is:
* not really good for performance
* a huge pain to manage all the `compilerOptions`, and to use the ts API in general.
* I’m sure I miss/supress some useful diagnostics along the way
* It interferes badly with rollup `watch` #15 

# How I think it should work in the future

I think to move forward, its needed to take a step back. Let some other tool worry about compiling typescript, and focus only on bundling pre-generated `.d.ts` files, similar to how [api-extractor](https://api-extractor.com/) works.

So it would use the typescript compiler as a parser only.

# Pros

* would follow *do only one thing and do it well*
* would massively simplify the plugin itself
* should improve performance slightly?
* would work better with `watch` mode
* would give users more freedom about how they want to compile their TS code (`--incremental`, etc), and about how they want to bundle their `.js` code.

# Cons

* would not be *single-dependency* / *zero-config* anymore
* would require users to deal with `.ts` -> `.js` / `.d.ts` compilation themselves
* `watch` mode would require two separate watchers (`tsc --watch` and `rollup --watch`?)

**Comment by timocov** [comment]
> and focus only on bundling pre-generated .d.ts files

Wow, I've thought about it in case of `dts-bundle-generator` too 🙂. The last what I decide is check if all files in the compilation is declaration files, then do not compile them again and just use the current compilation. It should allow to set declaration file as input file (you can do it already) and improve performance as well.

> would give users more freedom about how they want to compile their TS code (--incremental, etc), and about how they want to bundle their .js code.

It looks like there is a bug in the compiler (https://github.com/microsoft/TypeScript/issues/31696) and it can broke a pipeline in some cases (yeah, it don't work for composite projects only for now).

> watch mode would require two separate watchers (tsc --watch and rollup --watch?)

For me it's not a big problem. In current project I'm working on (https://github.com/tradingview/lightweight-charts) we don't use any plugin for rollup to work with TypeScript and compile it with tsc first and then bundle with rollup.

**Comment by aleclarson** [comment]
I'm in favor of this new direction. I'll be using [rollup-plugin-typescript2](https://www.npmjs.com/package/rollup-plugin-typescript2) instead, which has [its own caching system](https://github.com/ezolenko/rollup-plugin-typescript2/issues/119) and it works with `watch` mode [more or less](https://github.com/ezolenko/rollup-plugin-typescript2#watch-mode). Less work for you, too!

**Comment by Swatinem** [comment]
just published `1.0.0-alpha.0` to `next`, which does this :-)

Also, I think I found a workaround for `import * as X` and all the other namespace related issues :tada: 

I will try this version with one of my other projects, clean up the readme/docs a bit and then release it as `1.0.0` :-)

@timocov the @renovate-bot also pointed me to a recent regression in typescript related to exporting namespace declarations: https://github.com/microsoft/TypeScript/issues/31676 maybe that is also relevant for you.
