### ISSUE TITLE
Make `.ts` mode compatible with `rollup-watch`

### ISSUE THREAD

**Issue by Swatinem** [Swatinem/rollup-plugin-dts#35]
CC @aleclarson 

Hm, I completely forgot about #15 when I accepted #32.

Now (again), it uses `createProgram` ahead of time and queries that `program` instance inside the `load` hook. But the `program` instance is never invalidated based on *watch* feedback.

Thats also what I always meant when I said that using the typescript api for anything more than very trivial usecases is quite hard…

**Comment by aleclarson** [comment]
Yikes, I can't find any docs on integrating with TypeScript's watch-related API.

After some digging, I think [`ts.createWatchProgram`](https://github.com/microsoft/TypeScript/blob/d023427226ca3c7e900ddc65606a56e9f11802eb/src/compiler/watch.ts#L638-L646) is the right place to start.

**Comment by weeebdev** [comment]
Any updates on that?

**Comment by Swatinem** [comment]
I very much discourage using `.ts` mode. And I won’t be pouring in an unreasonable amount of effort into this.

**Comment by Swatinem** [comment]
I believe this was just fixed in #249
