### ISSUE TITLE
Consider using or forking typescript-estree

### ISSUE THREAD

**Issue by aleclarson** [Swatinem/rollup-plugin-dts#37]
See here: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree

**Comment by Swatinem** [comment]
I’m not sure this is of any real use, considering that the AST produced by the plugin is quite far removed from a *real* AST, see https://github.com/Swatinem/rollup-plugin-dts/blob/master/docs/how-it-works.md

What did you have in mind?

**Comment by aleclarson** [comment]
Not sure what you mean by "a *real* AST". I assume you're saying Rollup would choke on the AST produced by `typescript-estree`?

It seems like `typescript-estree` converts TypeScript to an ESTree-compatible AST, so I figured we could use that in order to avoid doing the same thing ourselves, but you would know best. ;)

**Comment by Swatinem** [comment]
The AST I produce has quite little similarity with what a direct typescript -> estree conversion. So I don’t think its useful
