### ISSUE TITLE
Is tree-shaking of tripleslash directives even possible?

### ISSUE THREAD

**Issue by Swatinem** [Swatinem/rollup-plugin-dts#38]
CC @aleclarson because this came up in #36 

I have never used those tripleslash directives manually before.
AFAIUI, they are kind of like `import "react"`, right? So you don’t import any specific item from them, but import them for their *side effects*, which are to define / extend some items in the global scope?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3173adb046702c25a053a3a1a14ba8774763098a/types/react/index.d.ts#L2805-L2806

I think its completely out of scope for this plugin to analyze any of the external dependencies for possible global scope access.

This might also be related to this setting:
https://github.com/Swatinem/rollup-plugin-dts/blob/c98789ee8d6ddea0f32262e48cab266ea257ac82/src/index.ts#L72

This will remove every empty `import "react"` if there is nothing from that specific import that one uses.

Well personally I consider messing with things in the global scope a red flag anyway, and I would rather discourage people from doing that, instead of putting too much effort into supporting such usecases.

**Comment by aleclarson** [comment]
Relevant quote from [TS docs](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html):
> A `/// <reference types="..." />` in a generated declaration file is added if and only if the resulting file uses any declarations from the referenced package.

So they're basically tree-shaked by the TypeScript compiler already. 🎉

**Comment by Swatinem** [comment]
Well yes, but it works on single files only, hence the need for this plugin in the first place.

Consider this:

```ts
// internal.ts
export type Unused = JSX.Element; // pulls in the directive, but is eliminated by rollup

export declare class Used {}

// index.ts
export { Used } from "./internal";
```
