### ISSUE TITLE
Error on export function delegates as default

### ISSUE THREAD

**Issue by doctorcode-co** [Swatinem/rollup-plugin-dts#42]
Hi
we have a destination file as below:
```
export default function autobind(): ClassDecorator | MethodDecorator;
export default function autobind(constructor: Function): void;
export default function autobind(prototype: Object, name: string, descriptor: PropertyDescriptor): PropertyDescriptor;
```
on compile time get error:

> Error: A module can only have one default export

How to fix this error?

**Comment by Swatinem** [comment]
Interesting. I *think* non-default exports will work, but I would have to find a workaround for `default`.
If you want to work around this limitation, you can try the following for now:

```ts
declare function autobind(): ClassDecorator | MethodDecorator;
declare function autobind(constructor: Function): void;
declare function autobind(prototype: Object, name: string, descriptor: PropertyDescriptor): PropertyDescriptor;

export default autobind;
```

**Comment by doctorcode-co** [comment]
> Interesting. I _think_ non-default exports will work, but I would have to find a workaround for `default`.
> If you want to work around this limitation, you can try the following for now:
> 
> ```ts
> declare function autobind(): ClassDecorator | MethodDecorator;
> declare function autobind(constructor: Function): void;
> declare function autobind(prototype: Object, name: string, descriptor: PropertyDescriptor): PropertyDescriptor;
> 
> export default autobind;
> ```

Thank you very much.
