### ISSUE TITLE
Expose extended modules in definition bundle

### ISSUE THREAD

**Issue by doctorcode-co** [Swatinem/rollup-plugin-dts#44]
Hi
Consider this code:
```
declare module react {
    export interface test {
    }
}
```
how i can expose this in final bundle?

**Comment by Swatinem** [comment]
I would have to look up how these TS module declarations work.

Because you don’t really `export` anything, it just modifies a global object as a side-effect, which is super weird…

**Comment by doctorcode-co** [comment]
In source of my plugin i extends react or knockout or vue and etc. this is declared in a ts file named react.extensions.ts (or ko.extenstions.ts) then in any file we need this plugin import it.
source of react.extensions.ts:
```
declare module react {
    export interface test {
    }
}
```
source of plugin:
```
import { test } from 'react';
...
const t = new test();
```
if **import { test } from 'react';** not declared then can not use test. Also, the user does not need to enter the separate definition file. 
The tsc emit it for me but dts plugin not emit this file in bundle.

**Comment by doctorcode-co** [comment]
dear @Swatinem :
Note that for extend jsx, need to emit declared global modules in final bundle.
```
declare global {
    namespace JSX {
        interface Element extends HTMLElement { }
        interface ElementClass extends ComponentBase {
        }
        interface ElementAttributesProperty { props: {}; }
    }
}
```

**Comment by Swatinem** [comment]
I played around with this a little bit, its a hard problem to solve though.

As a workaround, you can put all of your global augmentations into a separate file, and make it `external`, so it does not run through this plugin at all.
I think that should work.

**Comment by doctorcode-co** [comment]
your are true, it's hard to solved. I use gulp and fs to read source file and add to final destination file, temporary solved my problem. 
Thank you

**Comment by morlay** [comment]
```ts
declare global {
  namespace NodeJS {
    interface Global {
      second: Second;
    }
  }
}

export interface Second {}
```

```ts
// index.d.ts
export * from "./second";

export interface First {}

declare global {
  namespace NodeJS {
    interface Global {
      first: First;
    }
  }
}
```

could be transform to  (declare global will be merge by typescript, so i think coping could be fine)

```ts
declare global {
  namespace NodeJS {
    interface Global {
      first: First;
    }
  }
}
declare global {
  namespace NodeJS {
    interface Global {
      second: Second;
    }
  }
}

interface Second {}
interface First {}
export { First, Second };
```

but have to export `First`, `Second`.

@doctorcode-co @Swatinem 
how do think this behavier，just copy the global or module declaration?
