### ISSUE TITLE
import typeof + import typeof member access

### ISSUE THREAD

**Issue by gavar** [Swatinem/rollup-plugin-dts#51]
It seems the test case I submitted in issue #49 was not complex enough, here's another one

## Test
```
export type TypeScript = typeof import ("typescript");
export interface Test {
  rollup: import("rollup").RollupOptions;
}
```
## Expect
```
import * as ɨmport1_typescript__ from 'typescript';
import { RollupOptions } from 'rollup';
declare type TypeScript = typeof ɨmport1_typescript__;
interface Test {
  rollup: RollupOptions;
}
export { Test, TypeScript };
```

## Actual
```
import * as ɨmport1_typescript__ from 'typescript';
import { RollupOptions } from 'rollup';
declare type TypeScript = typeof ɨmport1_typescript__;
RollupOptions
export { Test, TypeScript };
```

> And these type-aliases are perfectly fine and valid code.

Intellij is going nuts reporting usage of non-ASCII symbols
Maybe it could be ASCII symbol like `$import` or `__import` for that?
![image](https://user-images.githubusercontent.com/3128402/61879995-b8fb9d80-aefc-11e9-84ae-1a7c1eb11ad4.png)

_Originally posted by @gavar in https://github.com/Swatinem/rollup-plugin-dts/issues/49#issuecomment-515053112_

**Comment by Swatinem** [comment]
@gavar sorry this took so horribly long, can you try again with `1.1.10`, that should fix these problems.
