### ISSUE TITLE
bundling multiple d.ts files Bug 

### ISSUE THREAD

**Issue by stropho** [Swatinem/rollup-plugin-dts#62]
Hi so I'm not entirely sure if this is a bug of `dts` plugin or rollup or little of both. Or maybe I'm just doing something wrong :-D

I'm combining many small  `.js` files into 1 index file. All these small files have their .d.ts definition. Therefore, I want to combine those `d.ts` files as well

`get-true.d.ts`
```js
export default function getTrue(...args: any): boolean
```
rollup entry point: `index.d.ts` or `index.ts`, it doesn't matter
```js
export {default as getTrue} from './get-true'
```
**Expected Result**
In an ideal world, after running this plugin with rollup I would like to have
```js
export function getTrue(...args: any): boolean
```

**Actual Result**
```js
declare function getTrue(...args: any): boolean

export { getTrue };
```
 1. I don't understand why the `declare` keyword appeared. Someone had an opposite problem https://github.com/Swatinem/rollup-plugin-dts/issues/24 . But I can live with that.
 2. What bothers me is the `export` at the end of the file
`tsc` **complains** about
 ```
function getTrue(...args: any): boolean

export { getTrue };
``` 
but `export function getTrue(...args: any): boolean` is just fine. I need such output for another tool: `typedoc`

If I set the property `external: (id) => true` in rollup config then, I think, I don't actually need this plugin :laughing:  . And I get
```js
export { default as getTrue } from './get-true';
```
`tsc` does not complain about anything in this last example

Can you advise what can I do about it? Am I doing something wrong?

**Comment by Swatinem** [comment]
1. thats how typescript outputs function declarations into `.d.ts` files.
2. rollup rewrites all imports/exports that way, all the exports are grouped at the bottom. And tsc should deal with them just fine that way.

What is the exact error you are seeing?

**Comment by stropho** [comment]
Hmm, I thought so. There is actually no `tsc` error.
It just seems that the `typedoc` tool is not able to read such output in order to generate documentation.

Well thanks for the response, sorry to bother you.
