### ISSUE TITLE
Error: end must be greater than start

### ISSUE THREAD

**Issue by couellet** [Swatinem/rollup-plugin-dts#63]
I'm not sure if the bug is in rollup directly or this plugin, but I can bundle my application correctly, but when I try to bundle my declaration files, I get this issue:

```
./dist/types/module.d.ts → ./dist/sdk.d.ts...
[!] Error: end must be greater than start
Error: end must be greater than start
```

Config:

```
{
    input: './dist/types/module.d.ts',
    output: [{ file: './dist/sdk.d.ts', format: 'es' }],
    plugins: [dts()],
  }
``` 

I was using Webpack DTS `webpack-dts-bundle` before with a similar config:

```
new DtsBundlePlugin({
    name: 'sdk',
    main: resolve('../dist/types/module.d.ts'),
    out: resolve('../dist/sdk.d.ts'),
    externals: true
}))
```

**Comment by Swatinem** [comment]
That does sound like a problem caused by the plugin. Is your project open source? Or can you create a simplified testcase that reproduces the problem?

**Comment by Swatinem** [comment]
This is not really actionable without some code snippet to reproduce. Please reopen with a failing testcase.
