### ISSUE TITLE
Getters not supported?

### ISSUE THREAD

**Issue by aleclarson** [Swatinem/rollup-plugin-dts#67]
```
[!] (plugin dts) Error: Could not load ~/dev/wana/src/auto.ts 
(imported by ~/dev/wana/src/core.ts): Syntax not yet supported
```

```
> 24 |     get test(): number | null;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Repo here: https://github.com/alloc/wana

`rollup-plugin-dts` version: tested both `1.1.5` and `1.1.11`

`typescript` version: `3.7.2`

**Comment by aleclarson** [comment]
Downgrading `typescript` to `3.6.4` worked for me

**Comment by krawaller** [comment]
Came here to report exact same issue. Started happening when upgrading TS (to `3.7.2`).

**Comment by krawaller** [comment]
Likely related to the [class field mitigations](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#class-field-mitigations#class-field-mitigations)?

**Comment by Swatinem** [comment]
getters and setters should work now with `1.1.12`
