### ISSUE TITLE
module declarations with label that is not an ID

### ISSUE THREAD

**Issue by GordonSmith** [Swatinem/rollup-plugin-dts#72]
The following declaration content fails:
```javascript
declare module 'd3-selection' {
...
}
```
With the following error:
```
[!] (plugin dts) Error: Could not load C:\Users\gordon\git\hpcc-js\node_modules\@types\d3-transition\index.d.ts (imported by C:\Users\gordon\git\hpcc-js\packages\graph\types\Graph.d.ts): namespace name should be an "Identifier"
```

**Comment by Swatinem** [comment]
hm, so from the AST structure, the `declare module` and `namespace` declarations are quite similar. Not sure how to best support these `declare module`, other than maybe just copying them 1:1…

**Comment by GordonSmith** [comment]
I think so - in this case the contents of the "d3-selection" (which is found in "d3-transition") is supposed to augment the contents of the "d3-selection" types.  (Like declaring two interfaces with the same name in TypeScript).

**Comment by morlay** [comment]
@Swatinem there a ugly way to support declare module

`` id or name will start different pos from last modifier (couldn't start with ModuleDeclaration because of may leadingComments)
```ts
      if (ts.isModuleDeclaration(node)) {
        if (node.modifiers && (node.name.pos - node.modifiers[node.modifiers?.length - 1].end) === 7 /* "module".length + 1 */) {
          itemTypes[node.name.getText()] = "module";
        } else {
          itemTypes[node.name.getText()] = "namespace";
        }
      } 
```

For module coping them 1:1 will be cool. this will resolve my issue #80 without extra comments.
