### ISSUE TITLE
Export "* as name from 'module'" not supported

### ISSUE THREAD

**Issue by Danielku15** [Swatinem/rollup-plugin-dts#86]
In my main library module export I am just bundling up the submodules I have with: 

```js
export * as module1 from './module1';
export * as module2 from './module2';
export * as module3 from './module3';
```

But I get a `Syntax not yet supported`. I'm using 1.4.0. Would be great if this plugin could support this syntax.

More info: 
https://www.typescriptlang.org/docs/handbook/modules.html#export-all-as-x

**Comment by Swatinem** [comment]
just publishes `1.4.1`, please try that ;-)
