### ISSUE TITLE
Support for star export

### ISSUE THREAD

**Issue by OmgImAlexis** [Swatinem/rollup-plugin-dts#94]
```ts
import { makeExecutableSchema } from 'graphql-tools';
console.log(makeExecutableSchema);
```

```ts
➜  tsup ./x.ts --bundle
Error parsing: /tmp/x.ts:1:8
'makeExecutableSchema' is not exported by node_modules/graphql-tools/dist/index.js, imported by x.ts
1: import { makeExecutableSchema } from 'graphql-tools';
           ^
2: 
3: console.log(makeExecutableSchema);
```

This is `node_modules/graphql-tools/dist/index.d.ts`.
```ts
export * from './Interfaces';
export * from './makeExecutableSchema';
export * from './mock';
export * from './stitching';
export * from './transforms';
export { SchemaDirectiveVisitor } from './schemaVisitor';
```

Here is `./makeExecutableSchema` which exports `makeExecutableSchema`.
```ts
import { GraphQLSchema } from 'graphql';
import { IExecutableSchemaDefinition, ILogger } from './Interfaces';
export declare function makeExecutableSchema<TContext = any>({ typeDefs, resolvers, connectors, logger, allowUndefinedInResolve, resolverValidationOptions, directiveResolvers, schemaDirectives, parseOptions, inheritResolversFromInterfaces }: IExecutableSchemaDefinition<TContext>): GraphQLSchema;
export declare function addCatchUndefinedToSchema(schema: GraphQLSchema): void;
export declare function addErrorLoggingToSchema(schema: GraphQLSchema, logger: ILogger): void;
export * from './generate';
```

**Comment by Swatinem** [comment]
> ```ts
> 'makeExecutableSchema' is not exported by node_modules/graphql-tools/dist/index.js
> ```

No idea why its trying to use the `.js` file? Maybe its `tsup` adding its own resolution step which interferes with this one?

Please try to use this plugin on its own, to make sure this is not a conflict with another plugin. Star exports should be supported just fine.

**Comment by Swatinem** [comment]
> Please try to use this plugin on its own

For that you would need to set the `respectExternals` option, since the plugin by default ignores all the things from `node_modules`.

**Comment by OmgImAlexis** [comment]
I’ll give those ideas a go today. Thanks.

**Comment by OmgImAlexis** [comment]
So this seems related. If I change it to `export * from './lib/index';` I have no issues.
Maybe it's not auto using index when hitting a directory?

`index.ts`
```ts
export * from './lib';
```

```
index.ts(1,15): error TS2307: Cannot find module './lib' or its corresponding type declarations.

Failed with following plugins used: hashbang, json, node-resolve, dts, size
Error: Could not load /Users/xo/code/unraid/core/index.ts: Failed to compile. Check the logs above.
    at error (/Users/xo/code/unraid/core/node_modules/rollup/dist/shared/rollup.js:217:30)
    at throwPluginError (/Users/xo/code/unraid/core/node_modules/rollup/dist/shared/rollup.js:17067:12)
    at Object.error (/Users/xo/code/unraid/core/node_modules/rollup/dist/shared/rollup.js:17806:24)
    at Object.load (/Users/xo/code/unraid/core/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1355:26)
    at /Users/xo/code/unraid/core/node_modules/rollup/dist/shared/rollup.js:18003:25
```

**Comment by Swatinem** [comment]
> Failed with following plugins used: hashbang, json, node-resolve, dts, size

You still have `node-resolve` in there. I’m pretty sure that is messing with the resolution somehow. Also, I don’t think you need `json` there either.

**Comment by aelbore** [comment]
@OmgImAlexis can you try to downgrade the typescript? maybe its an issue on latest version.
theres an issue also in sinon stub for latest version. or maybe try also to install tslib@1.13.0 version

**Comment by Swatinem** [comment]
Oh, I missed that this error is actually output by TS itself. Can you try to generate intermediate `.d.ts` files, instead of having the plugin generate those from `.ts` files on the fly?

**Comment by Swatinem** [comment]
I will close this, as I think the main cause was a misconfiguration. Please file a new issue and make sure to run this plugin on its own if this crops up again.
