### ISSUE TITLE
Cannot read property 'bind' of undefined, but only when compiling/bundling via script

### ISSUE THREAD

**Issue by darrickyee** [Swatinem/rollup-plugin-dts#97]
Originally posted to the Rollup repository, but I was asked to create an issue here, too:

https://github.com/rollup/rollup/issues/3578

@lukastaegert mentioned that this has to do with a "non-standard AST," but I do not know what that means :).

**Comment by Swatinem** [comment]
I think this was recently fixed in #95, I just didn’t come around to actually publish with the fix; will do that now.
