### ISSUE TITLE
Does not create bundled d.ts for lit-html

### ISSUE THREAD

**Issue by Spanoudakhs** [Swatinem/rollup-plugin-dts#99]
Searching for issues with `lit-html` in this repository I found nothing , so I decided to open an issue :

**Steps to reproduce :**

Create a new folder project and in that folder execute :
```bash
npm init -y;
npm install --save-dev rollup typescript rollup-plugin-dts;
npm install lit-html;
```
then create `./rollup.config.js` with content : 
```javascript
import dts from "rollup-plugin-dts";

const config = [
  {
	input: "./node_modules/lit-html/lit-html.d.ts",
    output: [{ file: "dist/my-library.d.ts", format: "es" }],
    plugins: [dts()],
  },
];

export default config;
```
then execute :
```bash
npx rollup -c rollup.config.js
```
and look at the creted d.ts file in the `./dist` folder .

**Expected behavior:**

the bundled d.ts file should not have any imports .

**Actual behavior:**

the bundled d.ts file has imports and in fact has no difference from the `./node_modules/lit-html/lit-html.d.ts` file .

**Comment by Swatinem** [comment]
I general, the plugin will by default ignore anything that comes from `node_modules` and treat that as external.
Other than that, looking at https://unpkg.com/browse/lit-html@1.2.1/lit-html.d.ts, the imports actually have a `.js` extension, so I’m not sure they are actually valid typescript, as typescript usually complains about file extensions.

Hm, maybe try again with forcing the plugin to inline all the externals?
https://github.com/Swatinem/rollup-plugin-dts/blob/ee097b9adcd3b67ba698fd6e27a99397ce34d7aa/src/index.ts#L13-L20

**Comment by Spanoudakhs** [comment]
@Swatinem So I did changed in `rollup.config.js` the following :
```javascript
import dts from "rollup-plugin-dts";

const config = [
	{
		input: "./node_modules/lit-html/lit-html.d.ts",
		output: [{ file: "dist/my-library.d.ts", format: "es" }],
		plugins: [dts({ respectExternal: true })],
	},
];

export default config;
```
and executed it and got some complains about circular dependencies , but it seems that I get intellisense for what I import . So I think it works so far .

**Comment by Swatinem** [comment]
Interesting. What is your usecase exactly? Usually you shouldn’t bundle your `node_modules`.

**Comment by Spanoudakhs** [comment]
@Swatinem I am using snowpack . I want snowpack instead of only doing that :
```
node_modules        web_modules
┣ lit-html          ┣ lit-html.js  
┣ mobx         =>   ┣ mobx.js
┗ mobx-utils        ┗ mobx-utils.js
```
do that :
```
node_modules        web_modules
┣ lit-html          ┣ lit-html.js  
┣ mobx              ┣ lit-html.d.ts
┗ mobx-utils   =>   ┣ mobx.js
                    ┣ mobx.d.ts
                    ┣ mobx-utils.js
                    ┗ mobx-utils.d.ts
```
Your plugin works so far for this purpose .
